### ISSUE TITLE
[1.10.2] [Bug] Compatibility Issue (Visual) with FTB Utilities/Vanilla

### ISSUE THREAD

**Issue by SnowShock35** [PrinceOfAmber/Cyclic#107]
Hello,

A quick bug to report regarding Cyclic for Minecraft 1.10.2, here are the details of the issue. . . 

### Important Information

* Minecraft 1.10.2 
* Minecraft Forge 12.18.1.2094
* Cyclic 1.10.2-1.7.8
* Other Mods:
    * FTB Utilities 2.1.0

### Issue Description

Crafting cake crafting table hides FTB Utils icons and potion effects.

### Issue Media

![Issue Screenshot #1](http://image.prntscr.com/image/cdd391c4c2c6443abba7a8a3a02620de.png)

**Comment by PrinceOfAmber** [comment]
Yeah i see whats going on there.  Thanks for reporting this.  Ill get a release out asap

**Comment by PrinceOfAmber** [comment]
**Cause:**
When i eat the 'Inventory Upgrade' cake, and use that button. the FTB utils HUD does stay in the top left. This is because its a "player type" of screen, and FTB Utils can detect this as part of the player.  But the way I set up the workbench screen. its basically an extension/clone of the Crafting table, so FTB Utilities treats it the same as it would the vanilla crafting table (and the hud does not show up in the vanilla crafting table, which is expected).  
**Solution:**
So i have to change the crafting gui to be more like a player screen (extend the player gui classes) so that other mods like FTBUtils knows this is a player inventory screen and not a table screen.  Possibly related to #69 .

This is not a quick fix like i thought, but i am looking into it.

**Comment by PrinceOfAmber** [comment]
Fixed in new release.  Rebuilt the inventory crafting screen.  https://minecraft.curseforge.com/projects/cyclic/files/2333207
