### ISSUE TITLE
[Feature] Something like magnum torch

### ISSUE THREAD

**Issue by GrzechuGrek** [PrinceOfAmber/Cyclic#112]
Something that work like magnum torch from EU(for MC 1.7.10). You put it and it's will prevent hostile mobs from spawn(even in darkness) in 32x32 or 64x64 blocks radius.

**Comment by PrinceOfAmber** [comment]
Thats a cool idea at least

**Comment by PrinceOfAmber** [comment]
Not the same as blocking spawns, but i can repel mobs away like the interdiction torch from equivalent exchange

  I just realized i can take my item magnet, and flip the vector in the opposite direction, make it hit mobs instead of items, and boom this should be a quick easy win.  ill try to work on that next week

**Comment by PrinceOfAmber** [comment]
Interdiction plate is in latest release :) https://github.com/PrinceOfAmber/Cyclic/releases/tag/1.8.11
