### ISSUE TITLE
[Crash] Server Block Miner

### ISSUE THREAD

**Issue by jules552** [PrinceOfAmber/Cyclic#113]
Hey,

When I place a Block Miner on my server, the server crash :/
Can you fix that problem ?

My crash server report if you need:
http://pastebin.com/ym97cWFu

Thank you for your work and have a nice day ;)

**Comment by PrinceOfAmber** [comment]
Sorry this caused you trouble, ill fix this asap

**Comment by PrinceOfAmber** [comment]
Hey Im pretty sure i fixed the problem so i put up a build to try and fix this.  I fired up a server with this build and the block miners are looking good.

Please let me know if this fixed it or if it still crashes or doesnt work for you, i dont have all the same core mods and things you have so it might be different.

Version 1.7.11
https://minecraft.curseforge.com/projects/cyclic/files/2333625

**Comment by jules552** [comment]
Still crashing ;(
My crash report: 
http://pastebin.com/T4VwGXkp

**Comment by PrinceOfAmber** [comment]
Thanks ill keep trying

**Comment by PrinceOfAmber** [comment]
Not sure yet, might be a conflict with spongeforge, since it works on other servers.  Regardless, im finding a way that might fix it.  Or at the very worst case, if this error happens i ill try to stop the server from crashing and just catch it..

..so that at worst the block just wont work and server stays up.  Build should be out tonight or tomorrow.

(The technical details are that, its a common practice for blocks like this to use a standard forge practice of making a "FakePlayer".  When i call the API to create a fake player, something from deep inside there is throwing an exception.)

**Comment by PrinceOfAmber** [comment]
New alpha build should be available in the link below once curse approves it..  i dont have time to setup my own instance of sponge to test it but i can hope for the best.  

Sorry if this doesnt fix it, might just be something incompatible with sponge and the way forge and cyclic use FakePlayers.  Disabling these blocks in the config is another option if this newest build doesnt work.  Also we could try reporting it to spongeforge developers, in case it is a problem in their code (which is just a theory)

https://minecraft.curseforge.com/projects/cyclic/files/2334071

**Comment by jules552** [comment]
Crash fixed ;) Thank you for your helping :)

**Comment by jules552** [comment]
The problem is fix, it was SpongeForge, the new update fixed this problems, Thank you for your helping !

**Comment by PrinceOfAmber** [comment]
Thanks!
