### ISSUE TITLE
Experience Pylon Won't Open

### ISSUE THREAD

**Issue by silvadollar** [PrinceOfAmber/Cyclic#1355]
Minecraft Version:  1.15.2

Forge Version: 31.1.0

Mod Version: 1.15.2-0.1.8

Single Player or Server:   Server

Describe problem (what you were doing; what happened; what should have happened):
I crafted an experience pylon and when I right click to access the pylon menu nothing happens. 

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Im trying to remake blocks to be more intuative and user friendly.  Like botania stile with less time staring at boring buttons botania style if possible.  (Plus i had soooo many bug reports in the 1.12 gui).

Ill update to add some info on the text message, such as if you use sugar when not enoguh it could say "41/50" since it takes 50 per bottle.

Also ill add a way to bottle EXP as well so sugar isnt only option

In block tooltip ill remind player to use a bottle or sugar.  A GUI might come back if we really need it.....

**Comment by Lothrazar** [comment]
in MC 1.16 it has a GUI and works with EXP fluid, 1.15 working as intended with sugar item
