### ISSUE TITLE
Question: Automated User

### ISSUE THREAD

**Issue by Okitengu** [PrinceOfAmber/Cyclic#1366]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.19.18

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):
Is there a way to output items that are stuck in input slot on automated user.  Trying to automate inputting enchantments into Ender Library with Automated User.  I've figured out the piping to import books into automated user and it works great.  Issue is when there is no space in library, so automated user cannot "use" the new enchantment book.  Trying to setup another Ender Library as an "overflow" in series, but books are getting stuck in the input slots.

**Comment by Lothrazar** [comment]
Yeah, the user doesnt have any way to know when the librarary is full.  And i cant really tell the user to just "dump the item if it doesnt work" because that will mess with all the other normal interactions.

There is only a finite number of enchantments, so having a big enough shelf and pointing the user at the library shoudl be the best strategy


Actually i noticed the limit is set to 64 enchantments in one slot.   Raising that up way higher will help.  so if theres room for 5 digits in the display text maybe i can make it 9999 
![2020-04-12_18 51 02](https://user-images.githubusercontent.com/621529/79085805-b04b3180-7cee-11ea-908a-698ff5d6b0e9.png)

**Comment by Okitengu** [comment]
I wasn't too worried about the library itself, since I saw from other
tickets it was already being worked on.  I was just curious if there was a
way to pull from the automated user's input if it couldn't use it.  Thank
you for your help.
