### ISSUE TITLE
Magic Bean missing?

### ISSUE THREAD

**Issue by chokoth** [PrinceOfAmber/Cyclic#1398]
Minecraft Version:  1.15.2

Forge Version:  31.1.39

Mod Version: 1.15.2-0.3.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): Magic bean isn't present. Looked completely through the creative menu and JEI and the bean doesn't show at all. I don't see anywhere in the config it could have been diabled (though I'm using the default config at the moment anyway). Was this item removed in 1.15? I didn't see anything on the curse page saying it was.

Let me know if you need any further information.

**Comment by Lothrazar** [comment]
the port for 1.15 is as yet incomplete, which is why version number starts with zero and its marked as beta on curseforge (0.3.4 is current, so when this reaches 1.0.0 it should have everything).   

The drop table will be different for this in 1.15 as well, trying to get an idea that makes sense for it

**Comment by Lothrazar** [comment]
all new features moved to my trello board to keep issue tracker clean :)
