### ISSUE TITLE
[Suggestion] [1.15.2] Additional Item/Feature Toggles

### ISSUE THREAD

**Issue by TheLastNoddy** [PrinceOfAmber/Cyclic#1406]
Just a request to add additional item/feature toggles to the config file.

Specifically in my case, I am building a mod-pack and would like to be able to disable the items that expand the players inventory and crafting grid. From my experience it can sometimes act a bit strange with kitchen-sink modpacks  and also feels a bit cheaty.

Thanks for all the hard work!

**Comment by SpiderKolo** [comment]
Following this idea, I would like to propose more specific Configuration files as well:
I would like for example to toggle some of the new enchantments, because they don't fit in my mind for my modpack I try to make.
- Beheading for example... well sure, we can get heads, but I don't feel like having dedicated enchantment for looting heads is necessary;
Or set lower maximum level for some enchantments
- Extra Jump having max of ten levels seems like overkill, but one, maybe two sounds reasonable;
Or tweak power level of enchantments themself
- Traveler seems like an interesting option, but it does negate the point of some of the enchantments we have - like Feather Falling.
Would be nice to be able to toggle few immunities off or to turn them into resistances instead of immunities.
Or Extra Jump again - it would be wonderful if we could toggle the high we could jump. 5 blocks might be fine for some modpacks, but some would like ot have less or more. Could be a great feature if you can also control max level of the enchantment.

**Comment by Lothrazar** [comment]
in 1.12 these already exist.
in 1.16 + toggling blocks on and off is not good practice, the forge devs and otehr devs are saying this can break worlds and stuff. what you CAN do is delete recipes and hide things in JEI.  I do have configs to disable any and all enchantments too
