### ISSUE TITLE
Pattern Replicator connected to RF crashes the server on tick

### ISSUE THREAD

**Issue by Enovale** [PrinceOfAmber/Cyclic#1462]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2854

Mod Version: 1.20.3

Single Player or Server: Dedicated Server, also occurs in singleplayer

Describe problem (what you were doing; what happened; what should have happened):

I place a Pattern Replicator, and connect it to any kind of RF source, and the server/game crashes. It should have powered the replicator and functioned normally. Upon reloading the world/restart the server, it crashes again once the server does its first tick.

Log file link:

https://pastefs.com/pid/221438

**Comment by Frikkle** [comment]
Just encountered exactly this issue when debugging another issue related to the Pattern Replicator and consistent world-crash behaviour after that.

I created this issue in the Enigmatica 2 Expert modpack because I first wanted to do more tests before "blaming" Cyclic. Our pack is quite huge, but since I noticed this issue already exists here, just a quick reference to the issue on our repo: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1782

**Comment by Lothrazar** [comment]
copying a snipped for reference
```
Caused by: java.lang.NullPointerException
   at com.lothrazar.cyclicmagic.block.builderpattern.TileEntityPatternBuilder.getCenterSource(TileEntityPatternBuilder.java:241) ~[TileEntityPatternBuilder.class:?]
```

**Comment by Lothrazar** [comment]
1.20.5 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3040547
