### ISSUE TITLE
1.16.3 Harvester does not harvest the range the preview shows

### ISSUE THREAD

**Issue by Letoric** [PrinceOfAmber/Cyclic#1487]
Minecraft Version: 
1.16.3
Forge Version: 
34.1.0
Mod Version: 
0.7.1
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):
Place harvester, turn on preview, preview shows roughly 17x17, garden is a 15x15, the range it actually seems to harvest is 15x9 on my garden. 9 blocks in front of it, 7 blocks on either side of it

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
The range previewed is 19x19 (radius 9), to include the preview bounding box.
The range harvested is 19x19 also, _but not where you'd expect_.

Due to a missing offset in the harvest code, it's actually harvesting a 19x19 area centered on the Harvester, instead of the area in front of the harvester as the preview implies.

**Comment by Letoric** [comment]
In my world, it is not. I am not sure why it's that way, but it is working
the measurement I mentioned

**Comment by Letoric** [comment]
Nm I understand. Looking forward to the fix

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3073113
