### ISSUE TITLE
"Growth" Enchantment is unusable.

### ISSUE THREAD

**Issue by Mysteriaa** [PrinceOfAmber/Cyclic#1490]
Minecraft Version:  1.15.2

Forge Version: 31.2.41

Mod Version: 0.7.0

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened): Basically what the title says. The Growth enchantment is essentially unusable. In the below image, there'd normally be a list of items that accept this enchantment, but it's blank in the image.

Log file link: n/a

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/67705660/94753497-69183200-035c-11eb-8686-706be88987e2.png)

**Comment by trunksbomb** [comment]
The "list of items that accept this enchantment" tooltip is from another mod, so the tooltip not appearing for this item is probably something the developers of that mod would need to fix.
The maximum level of Growth is 3, and it's applicable to books and hoes. When a hoe with the Growth enchantment is held, it applies random growth ticks to crops in a radius around the player.

Did you try applying the enchanted book from your screenshot to a hoe?

**Comment by Mysteriaa** [comment]
> 
> 
> The "list of items that accept this enchantment" tooltip is from another mod, so the tooltip not appearing for this item is probably something the developers of that mod would need to fix.
> The maximum level of Growth is 3, and it's applicable to books and hoes. When a hoe with the Growth enchantment is held, it applies random growth ticks to crops in a radius around the player.
> 
> Did you try applying the enchanted book from your screenshot to a hoe?

I have--it doesn't work with the hoe. 
![image](https://user-images.githubusercontent.com/67705660/95018214-3d32d000-062c-11eb-9af3-8cd851d9d14c.png)

**Comment by trunksbomb** [comment]
Ok, but it still seems like a mod interaction issue more than a Cyclic thing. I have Cyclic 0.7.0 on MC 1.15.2 and I can enchant an iron hoe with Growth III.

You've got a Growth V book, which is not possible without some other mod (or maybe a command) allowing you to go over the maximum levels of Growth.

![image](https://user-images.githubusercontent.com/1904331/95020071-e979b400-0636-11eb-975b-01957eed8057.png)

Even if I cheat in a Growth V book, I can still apply it to the Hoe but the level just maxes out at 3:

![image](https://user-images.githubusercontent.com/1904331/95020229-fc40b880-0637-11eb-9180-88f8be929e74.png)

![image](https://user-images.githubusercontent.com/1904331/95020222-efbc6000-0637-11eb-826f-183d9e0ddb70.png)

This is definitely a compatibility issue, most likely caused by another mod.

**Comment by Lothrazar** [comment]
yeah most likely
