### ISSUE TITLE
Solid Ender Eye not working

### ISSUE THREAD

**Issue by SoNiice** [PrinceOfAmber/Cyclic#1517]
**Minecraft Version**: 1.16.3

**Forge Version**: 34.1.15

**Mod Version**:  0.8.0

**Single Player or Server**: Server

**Describe problem (what you were doing; what happened; what should have happened)**:

Solid Ender Eye not throwing Ender Eyes at all, literally not working.

**Comment by trunksbomb** [comment]
Can only replicate when I generate a world that has "Generate Structures" turned off.
Works otherwise.

**Comment by Lothrazar** [comment]
I just tested on a server, and it flew out and found it.  
It wont launch if it cannot find any strongholds in the dimension / world type.

**Comment by SoNiice** [comment]
We've tested both on singleplayer and server, structures are enabled and we also found the end portal with vanilla eyes. Just the reusable one from Cyclic isn’t working. Is it related to the vanilla command (locate) isn’t working either regarding the stronghold?

**Comment by Flatts3000** [comment]
I have the same issue with All the Mods 6 - 1.2.1 - multiplayer server. Right clicking in the air with the solid ender eye does nothing. Regular eye of ender flies off in a specific direction.

**Comment by trunksbomb** [comment]
I was able to get it to replicate in ATM6 1.3.2. Regular Eye of Ender worked, but Reusable didn't.

So far, I'm 0/4 on being able to replicate it with just Cyclic installed.

I checked the code and other than some obvious changes (not decrementing stack size, not allowing it to be placed in an End Portal Frame), the code is identical. There's only two spots that the code could not throw the eye and that's when it's being called from the client side or if it failed to find a stronghold (true of regular Eye of Ender as well).

I grabbed the seed from my ATM6 world where it didn't work and loaded it up in a fresh 1.16.4 world with the same seed -- I could use the reusable Eye, no problem. It's got to either be a Forge mappings issue or a mod interaction issue. I suspect it may be a Forge mappings issue because both Cyclic and the decompiled 1.16.3 code it's built against call an unmapped function to find the stronghold (in 1.16.3, `((ServerWorld)worldIn).getChunkProvider().getChunkGenerator().func_235956_a_()`) but then again it worked in my 1.16.4 world with just Cyclic so maybe not? I'm leaning toward mod interaction.

**Comment by trunksbomb** [comment]
I just loaded up a separate 1.16.4 modpack to test a different issue and was able to replicate again.

**Comment by Lothrazar** [comment]
Ill update to latest mappings and run locally in 1.16.4 .  Seems it migh be specific to servers and possibly larger modpacks

**Comment by trunksbomb** [comment]
To be more specific, here are the scenarios I tested:

1.16.3 Dev environment: Works
1.16.4 Dev environment: Works
1.16.4 All the Mods 6 pack: Doesn't work
1.16.4 Survival in Chaos pack: Doesn't work
1.16.4 MultiMC instance with same seed as the ATM6 pack: Works

So even in 1.16.4, it works fine when Cyclic is the only mod present.

**Comment by trunksbomb** [comment]
I'm playing around in All the Mods 6 pack right now, which has 0.9.2 of Cyclic.

~I decided to look for the Stronghold using Ender Eyes and found that it led me on a bit of a wild goose change. The eyes seemingly changed directions slightly about 3-4 times and led me about 7000 blocks away from where I started -- usually you'll travel much less.~ Turns out I travelled just far enough past the Stronghold that the eyes started locking on a new one. I was using an Iron Jetpacks Jetpack, so I was moving somewhat fast. I went back and found the stronghold I had been heading toward originally.

~When I finally found a Stronghold, I exhausted (to my knowledge) every connected pathway in there and couldn't find it. I gave myself a stack of Ender Eyes and just started spamming them while mining toward where they headed and it eventually led me to a dead end -- nothing. No End Portal.~ I looked up how Eyes work and they don't actually lead you to the portal, but rather the first-generated feature in the Stronghold. I went back in Spectator mode and found the Portal down a hall I had mistook for a dead end.

I gave myself a Solid Ender Eye at this point and noticed it didn't work (as confirmed in a previous comment).

![image](https://user-images.githubusercontent.com/1904331/100524905-0ab7d600-318a-11eb-98c8-c42a779d5347.png)

~That's the path I took. I just went back to my base and confirmed that my initial heading was correct so it definitely switched me to a different Stronghold at least once.~

All that's to say -- there's definitely something weird going on, but I don't think it's specifically Cyclic.

**Comment by BugmanBugman** [comment]
For me, I believe I have found the cause. Not sure about the OP, but the mod causing it to break is Repurposed Structures (tested it with just that and cyclic so I can confirm). I believe this is because Repurposed Structures replaces the vanilla stronghold with its own version, and edits the vanilla ender eye to direct to that. The solid ender eye probably breaks since it can't detect the vanilla stronghold.

**Comment by trunksbomb** [comment]
Good catch. I've tried in two separate modpacks and both also have Repurposed Structures in them (1.16.4 versions 2.3.0 and 2.3.2).

**Comment by trunksbomb** [comment]
Opened an issue over there to track this.

They use a mixin to modify Ender Eye behavior. It's now looking for the structure `RSStructures.STONEBRICK_STRONGHOLD` instead of vanilla's `Structure.STRONGHOLD`.

https://github.com/TelepathicGrunt/RepurposedStructures/blob/master/src/main/java/com/telepathicgrunt/repurposedstructures/mixin/EnderEyeStrongholdLocatingMixin.java

**Comment by TelepathicGrunt** [comment]
@trunksbomb  It's actually checking vanilla's too. What the mixin does is it takes the resulting chunkpos of vanilla's stronghold location, then compares it to the chunkpos of repurposed structure's two other strongholds and returns the closest chunkpos to the player. The issue is the Solid Eye of Ender overrode the method I mixin into and so, it lost the functionality I added to vanilla's item. We will work together on a solution to this so keep watching this thread

**Comment by TelepathicGrunt** [comment]
@Lothrazar Can you check out my comment here? I explain how the issue is occurring between our mods and I think it can be a simple isModLoaded check and then grab the chunkpos of my strongholds. Then just return the one that is closest to player. It shouldn't be too hard to do mod compat like that but just let me know if you need help and I'll try and PR a fix
https://github.com/TelepathicGrunt/RepurposedStructures/issues/38#issuecomment-738951917

**Comment by trunksbomb** [comment]
The Solid Ender Eye doesn't actually extend the vanilla Ender Eye, so it's less of overriding and more that it duplicates the vanilla code. Thanks for all the info, either Lothrazar or myself will try to knock this out soon since the issue keeps cropping up.

**Comment by trunksbomb** [comment]
![image](https://user-images.githubusercontent.com/1904331/101222628-258dbd00-3658-11eb-83be-ff44722721e1.png)

Wrapping up implementation now, will post PR soon.
