### ISSUE TITLE
Inventory Sorting the contents of a Crate moves the Player inventory items into AND sorts Crate

### ISSUE THREAD

**Issue by IamStig** [PrinceOfAmber/Cyclic#1527]
Minecraft Version: 1.16.3

Forge Version: 34.1.15

Mod Version: 0.8.1

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened): I am using Inventory Tweaks...This does not happen in vanilla chests or any other inventory that I have seen.... only in the Cyclic crate.

Open Cyclic crate, left click AZ UI button or click mouse wheel/middle button to sort contents and the players inventory is moved into the crate and sorted. Player inventory should not move.
I double checked and vanilla chests and Iron chests function correctly.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
Inventory Tweaks doesn't exist in 1.16.3, are you using Inventory Tweaks Renewed?

**Comment by IamStig** [comment]
Sorry..Yes Inventory Tweaks Renewed. The name on the jar file is simply - "invtweaks-1.16.2-1.0.0.jar" which is the reason I forgot the Renewed title. Also while the file says 1.16.2 the curse page lists it as supporting 1.16.1/2/3.

**Comment by Lothrazar** [comment]
for reference https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-renewed/files/3031920

**Comment by trunksbomb** [comment]
![image](https://user-images.githubusercontent.com/1904331/101128528-ddc25380-35cd-11eb-8873-af36ccbec7be.png)

I was finally able to get InvTweaks Renewed working in dev. I had to compile it and create my own Maven repository to make it work lol.

Now to figure out why this happens.

**Comment by IamStig** [comment]
I am pleased to see you guys still on this, well... not pleased it is proving tough but pleased your dedicated to solving it. RESPECT

**Comment by trunksbomb** [comment]
So the basic rundown of how InvTweaks is working is as follows:
  - Detect middle-click (default "sort_either" button) inside a Container
  - Find the slot underneath the mouse
  - Check if that slot is an instance of `PlayerInventory`
  - Based on that, send a sort request to the server either as a player inventory sort, or a container sort

The sorting is handled by `Sorting#executeSort()`. The process goes:
  - double-check that a container is still open
  - look for any config entries that disable sorting in this container and don't sort if disabled
  - Check for valid slots to sort:
    - look for any config entries that explicitly tell InvTweaks what slots it can sort (this would be the workaround solution, btw, to this issue) and use that to determine the slots to sort
    - otherwise, get `Container#inventorySlots` and iterate over them in a `stream`, only keeping the slots that a) aren't an instance of `PlayerInventory` and either b) have a stack in them that is valid for that slot or c) are empty

Everything beyond this point shouldn't matter because the above is where InvTweaks is throwing in player inventory slots into the mix.

Here's the discrepancy:
  - Open a Vanilla chest, middle-click in player inventory section to sort: it's a Player Sort
  - Open a Vanilla chest, middle-click in the chest section to sort: it's a Container Sort
  - Open a Cyclic crate (or any other container in this mod) and middle-click in player inventory section to sort: it's a Container Sort
  - Open a Cyclic crate and middle-click in the crate section to sort: it's a Container Sort

Therein lies the problem -- why is Cyclic's inventory counting as a container regardless of where we clicked? As mentioned in the duplicate issue, I've had this happen with other mods as well so it's not just a Cyclic issue.

Continuing to investigate.
