### ISSUE TITLE
[1.16.3]Experience boost free xp offhand tool ?

### ISSUE THREAD

**Issue by Gayanfalor** [PrinceOfAmber/Cyclic#1548]
Minecraft Version: 1.16.3

Forge Version: 34.1.25

Mod Version:  1.16.3 -0.8.3

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Having an enchanted shovel with experience boost 1 in offhand and harvesting leaves shrooms with bare hand or tools on main hand gives xp.

Is that intended or not ? its a bit like https://github.com/Lothrazar/Cyclic/issues/1416

Thanks

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
Can confirm that's how it's working, not sure if it's intended.

https://github.com/Lothrazar/Cyclic/blob/0515f279e5c55f697905436fd509280422f7e117/src/main/java/com/lothrazar/cyclic/enchant/EnchantXp.java#L29

The call to that method does intentionally get the enchantment level from both tools so it may be intentional, but could easily be changed to call `getCurrentLevelTool(player.getHeldItemMainhand())` instead since you can only break things with your mainhand item.
