### ISSUE TITLE
Crash on death from zombies

### ISSUE THREAD

**Issue by Letoric** [PrinceOfAmber/Cyclic#1571]
https://pastebin.com/Td9whYKV

crash log contains the details that I can provide, it was literally fresh boot, somebody died to a zombie, and the server crashed. Versions are in the crash log also, but it's the 0.91 latest release

**Comment by JaxsonYorke** [comment]
So i have the same problem and i am getting the same crash report 
i have done some more tests on this subject
if you /kill the server doesn't crash 
same if you /kill with levels
if you kill yourself with a potion the server doesnt crash
It only happens if you die from any mob in the game even if you don't have levels
it also happens if you die in lava

**Comment by Lothrazar** [comment]
Fix coming tonight in 0.9.2
