### ISSUE TITLE
Crashing from death 1.16.3

### ISSUE THREAD

**Issue by IchigoGames** [PrinceOfAmber/Cyclic#1572]
Minecraft Version: 1.16.3

Forge Version: 34.1.42

Mod Version: Cyclic-1.16.3-0.9.1

Single Player or Server: singeplayer

Describe problem (what you were doing; what happened; what should have happened):
is not giving a crash report but i tested with and without cylic with cylic if you die not mater how you die you will CTD
here is info from log that lead me here before finding out others had this issue this is not a crash report as it does not create one just ctd exit code 0

also this may be a duplicate issue as but it also looked like that was fixed in hotfix not sure if this is the same crash.

Log file link:
https://pastebin.com/c2LGtjqG this is from console in singeplayer game

https://www.dropbox.com/s/m043yt9ej5d55rd/latest.log?dl=0

**Comment by IchigoGames** [comment]
i think this is the main reason for crash Caused by: java.lang.NullPointerException
	at com.lothrazar.cyclic.enchant.EnchantXp.handleEntityDropEvent(EnchantXp.java:37)

**Comment by JaxsonYorke** [comment]
So i have the same problem and i am getting the same crash report
i have done some more tests on this subject
if you /kill the server doesn't crash
same if you /kill with levels
if you kill yourself with a potion the server doesnt crash
It only happens if you die from any mob in the game even if you don't have levels
it also happens if you die in lava

**Comment by Lothrazar** [comment]
Fix coming tonight in 0.9.2
