### ISSUE TITLE
Gloom enchant on mob kicks player from server. 1.16.4

### ISSUE THREAD

**Issue by IchigoGames** [PrinceOfAmber/Cyclic#1591]
Minecraft Version: 1.16.4

Forge Version: 35.1.0

Mod Version: Cyclic-1.16.3-0.9.2

Single Player or Server: server

potential issue with gloom enchant on server user fighting a mob that as gloom enchant on them kicks the user from the server its not a crash so i cant give you any crash report 

Log file link:
Server logs
https://www.dropbox.com/s/xu4g4czu0lda19w/debug.log?dl=0
https://www.dropbox.com/s/carbv6h587qkq4e/latest.log?dl=0
User log
https://www.dropbox.com/s/gin4dy3clp1vigl/user%20latest.log?dl=0

**Comment by IchigoGames** [comment]
could also be a mod conflict issue with Apotheosis-1.16.3-4.4.1 as i know that mod some times makes echants from mods stronger then dev ever intended them to be

and no before you ask i cant test this by it self i only have 1 public server and im using it for modpack if you need anymore logs let me know

iv heard some one put it a request to add option to disable this enchant that would also help if your unable to repeat this issue

**Comment by IchigoGames** [comment]
iv heard some one put it a request to add option to disable this enchant that would also help if your unable to repeat this issue

**Comment by AhSchoo** [comment]
To add to this, I'm seeing effects on the player with potion effect IDs beyond the vanilla list. IDs 33, 39, and 63 on one player.

**Comment by IchigoGames** [comment]
https://www.dropbox.com/s/m5l1p2jfwsacxch/89c097d6-eaf1-44bc-85e2-7944dab5f0b6.dat_old?dl=0
https://www.dropbox.com/s/xm171wgn37wcosd/89c097d6-eaf1-44bc-85e2-7944dab5f0b6.dat?dl=0

**Comment by trunksbomb** [comment]
Thanks for all the details, I'll check on this in a few hours.

I wrote the Gloom enchantment -- it just pulls a list of negative/harmful effects from the Forge Potion Effect registry, including mod-added effects. I'll try to get a server environment setup to test this as well.

**Comment by trunksbomb** [comment]
I think it might be as simple as a missing server/client desync issue -- ie, effects being applied on the client side as well as the server. I'm submitting a PR that prevents it.

More specifically, your log indicates that the user is getting disconnected (this time) when trying to perform logic on the Radiation effect from PlantTech 2 -- likely what's happening is that because the Radiation effect doesn't know what to do from the client-side (since it's meant to only be processed server-side), it crashes the player.

**Comment by IchigoGames** [comment]
this might not be fixed some one just had it happen to them on my server after updae

**Comment by IchigoGames** [comment]
it could be it needs to be fixed on both mods side

**Comment by IchigoGames** [comment]
https://bitbucket.org/kaneka/planttech2/issues/104/crash-due-to-radiationeffect i also had a crash looking at the crash report it seem like a issue with planttech only but could be related to gloom if so this is the first time some one has crashed from it might be worth a look.

**Comment by trunksbomb** [comment]
If both the client and server have Cyclic 0.9.3, it should be fixed _if the issue was indeed what I submitted the PR for_ which was running server-side code on the client causing a crash and/or lingering potion effect icons.

If there's another issue, then I think it would be on the PlantTech author to fix. What I'm gathering from all of your crash reports is that their `RadiationSickness` potion effect is trying to get their custom Radiation capability for the player, not finding it, and crashing. I'm guessing that, within PlantTech, you can only get the Radiation effect how the mod author intended and therefore the Radiation capability will always be present and so no crash will occur. Any mod that adds an ability to arbitrarily apply potion effects like we're doing here would also encounter this issue.

The best course of action, in my opinion, is for the PlantTech author to gracefully handle a situation where the Radiation effect is applied on an entity that doesn't have the Radiation capability.

On this side, we could possibly implement an "effect blacklist" so we can selectively tell the Gloom enchantment to not apply that effect.

**Comment by trunksbomb** [comment]
https://bitbucket.org/kaneka/planttech2/src/1.16.x/src/main/java/net/kaneka/planttech2/effects/RadiationSickness.java#lines-21

Mod author would check to make sure the `RadiationEffect` capability exists here in their `if` statement before attempting to fetch it.

**Comment by IchigoGames** [comment]
The mod author Removed the RadiationEffect

**Comment by trunksbomb** [comment]
https://bitbucket.org/kaneka/planttech2/issues/104/crash-due-to-radiationeffect

Fixed here by mod author with explanation. This issue can be closed.

**Comment by IchigoGames** [comment]
well it all ready was but ok lol
