### ISSUE TITLE
Excavate Enchant doesnt work on Redstone Ore

### ISSUE THREAD

**Issue by Shorepion** [PrinceOfAmber/Cyclic#1597]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.1.41

**Mod Version:** Cyclic-1.16.4-0.9.3.jar

**Single Player or Server:** both

**Describe problem (what you were doing; what happened; what should have happened):**
Excavate enchant doesnt work on redstone ore:

Tried it with Vanilla Minecraft Tools and with SilentGear Pickaxe:
https://youtu.be/e3vCrjgoEvc

Probably because, when you touch redstone the state of the block changes (red particles+glowing state)?

**Comment by trunksbomb** [comment]
I was able to replicate, but it shouldn't have anything to do with how redstone is able to change. When checking for surrounding blocks to harvest, it's comparing that the two base blocks are the same, so it disregards the block's state (lit vs unlit). Needs further research.

**Comment by Lothrazar** [comment]
i can make a quick bandaid fix that target redstone ore, because it just should work that way. For the end user they should work like rotated logs, even though the lit ore is a different state.  Maybe also lit and unlit furnaces.   but yeah long term if theres any other blocks that work in a similar way where different blocks need to be grouped together then some robust or config system should come in

**Comment by Lothrazar** [comment]
According to source code, tool type 'pickaxe' is not a valid harvesting tool for redstone or when its lit up


[08:19:43] [Server thread/INFO] [co.lo.cy.ModCyclic/]: pickaxe  TOOL NOT EFFECTIVE ON Block{minecraft:redstone_ore}[lit=true]

From if (block.isToolEffective(world.getBlockState(pos), type)) 

https://github.com/Lothrazar/Cyclic/blob/40cd42a3869d05b5a3640918737cb3e0221499bb/src/main/java/com/lothrazar/cyclic/enchant/EnchantExcavation.java#L103

IDK where root cause is, forge or vanilla but ill add a workaround

**Comment by trunksbomb** [comment]
That's uh... weird. Good catch, though.
