### ISSUE TITLE
[1.16.4] Harvester will harvest the pumpkin seeds...

### ISSUE THREAD

**Issue by scottctd** [PrinceOfAmber/Cyclic#1601]
Minecraft Version: 
1.16.4
Forge Version: 
35.1.6
Mod Version: 
Cyclic-1.16.4-0.9.3.jar
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):
The harvester should not harvest the pumpkin seeds I think.
Only harvest the products is a good way.
Also, the energy bar seems inverted? (idk whether this design is intentionally)

Log file link:
None

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/35100768/100588939-64a4d100-332d-11eb-9ef6-325edb9d9b89.png)

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by trunksbomb** [comment]
Loaded up test world and confirmed that the Harvester "harvests" the mature pumpkin stem itself instead of waiting for there to be a pumpkin attached to it. Ideally it should detect that it's a melon-type plant and look for the actual melon/pumpkin/whatever instead of breaking the stem. I imagine this change wouldn't be too difficult to implement.

As for the GUI -- I don't know if it was ever specifically intentional but that's how it's coded.

**Comment by scottctd** [comment]
This is a test world with only cyclic and Mek(Power supply)
Initially, the left is melon seeds, and the right is pumpkin seeds.
![image](https://user-images.githubusercontent.com/35100768/100682227-957a1a00-33b0-11eb-99f5-e49e506c6ca6.png)
After they became mature:
![image](https://user-images.githubusercontent.com/35100768/100682322-ce19f380-33b0-11eb-8633-e3190521d84b.png)
The stem and the pumpkin (and the melon) will all be harvested.
I believe this should be a bug or ... feature?

Sorry for troubling and thanks for providing such a good mod!
