### ISSUE TITLE
Change Request: Gentle Harvester number of tiles interacted with on execution

### ISSUE THREAD

**Issue by Letoric** [PrinceOfAmber/Cyclic#1639]
Minecraft Version: 
1.16.4
Forge Version: 
35.1.13
Mod Version: 
1.0
Single Player or Server:
Both

Current situation:
 The gentle harvester change recently to improve server performance has rendered the harvester nearly unusable to a lot of players as it takes over 2 minutes for it to go through all tiles of a garden now. 

Proposed change: 
 On each execution (maybe 20 ticks?), execute the gentle harvest on all tiles it covers. This reduces the constant checks it was doing before your last update, but still makes it very usable to people who have high growth speed gardens from mods like Mystical Agriculture growth accelerators, reliquary lilypads of fertility, farming for blockheads speed fertilizer.

**Comment by kaweepatinn1** [comment]
totally agree. farming is impossible after that update

**Comment by LoffyLV** [comment]
> totally agree. farming is impossible after that update

Yeah, it's really bad, while before harvesters were doing just great, 2 of them harvested 11x11 with supremium watering can sped up mystical agriculture field now it takes like 2 minutest to harvest the field once. Probably will have to roll back to beta because on our server (ATM6) only other fast "gentle" harvesting option is to put down item user on top of every single crop and that seems to make nice lag when you have few thousand of them put down.. those few dozen harvesters made 0 lag in comparison.

**Comment by kaweepatinn1** [comment]
yeah, i tried using create because of the update but one small field already reduced my tps from 20 to 2 so there seems to be an issue with that. rn i’m just using 16 harvesters for a 17by17 field, it’s slower and less efficient but still works.

**Comment by Lothrazar** [comment]
harvester speed added in version 1.1.0 +

**Comment by Letoric** [comment]
Harvester Speed is not showing up in the config even if I have it freshly
generated. I also got in game and checked the harvester UI and do not see a
speed config. Can you help an old man out? :P

Thanks Lothrazar

**Comment by Lothrazar** [comment]
people just whine about lag when it hits multiple blocks at once
