### ISSUE TITLE
Server Crash on crafting table GUI open

### ISSUE THREAD

**Issue by khazoda** [PrinceOfAmber/Cyclic#1645]
Minecraft Version: 
1.16.4

Forge Version: 
35.1.13

Mod Version: 
Cyclic-1.16.4-1.0.0.jar

Single Player or Server:
Server

Describe problem (what you were doing; what happened; what should have happened):
Right clicked crafting table, server crashed.

Log file link:
[crash-2020-12-25_03.12.57-server.txt](https://github.com/Lothrazar/Cyclic/files/5740805/crash-2020-12-25_03.12.57-server.txt)

Video/images/gifs (direct upload or link):

**Comment by trunksbomb** [comment]
Cause of the crash is trying to get the display name for the GUI of the Workbench.

Looks like this is the only `getDisplayName` override that uses `return this.getBlockState().getBlock().getTranslatedName();` instead of `return new StringTextComponent(getType().getRegistryName().getPath());` Would be an easy enough fix to go back to the old style but I wonder why it doesn't exist.. Cyclic 1.0.0 is compiled against Forge 35.1.13 just like you're using according to crash log.
