### ISSUE TITLE
Workbench crashes server on clicking "empty grid" button

### ISSUE THREAD

**Issue by khazoda** [PrinceOfAmber/Cyclic#1652]
Minecraft Version: 
1.16.4

Forge Version: 
35.1.13

Mod Version: 
Cyclic-1.16.4-1.0.1.jar

Single Player or Server:
Server

Describe problem (what you were doing; what happened; what should have happened):
The workbench server crash issue was fixed  (#1645) with the latest cyclic release, but now the server crashes if the empty grid button is clicked in the workbench. I tested this with items in the grid and with no items in the grid, and both times my server crashed.

P.S the name displayed in the workbench is "workbench" not "Workbench", which is just an aesthetic issue and I didn't think it warranted a seperate issue

Log file link:

[crash-2020-12-28_04.39.52-server.txt](https://github.com/Lothrazar/Cyclic/files/5745700/crash-2020-12-28_04.39.52-server.txt)

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/42558699/103185977-ab4b0400-48b6-11eb-81a8-76b337d27dfe.png)

**Comment by trunksbomb** [comment]
Cause of the crash is what I guess you can call a "conflict of intent".

I believe @Lothrazar had intended to use the `IContainerCraftingAction` to make sure that any implementing class also implements the `transferStackInSlot` method, which is normal, but because (presumably) it's the same method signature as `ContainerBase#transferStackInSlot` which is itself an override of the same method in `Container`... it's causing unintended behavior.

![image](https://user-images.githubusercontent.com/1904331/103187148-4df08c00-4891-11eb-8af5-ee23e3ab70f2.png)

This can be fixed three ways.
1. Also check for instance of `ContainerBase` and cast to that instead of `IContainerCraftingAction` in `PacketCraftAction`
https://github.com/Lothrazar/Cyclic/blob/9c7ce2ef560a526fde4876735af1cc8dcd6e3d96/src/main/java/com/lothrazar/cyclic/net/PacketCraftAction.java#L60-L64

2. Change the method name in `IContainerCraftingAction` and call that instead. For instances of that interface that don't have a custom `transferStackInSlot` implementation, have the body of this newly-renamed method return `Container#transferStackInSlot`
3. Don't declare `transferStackInSlot` in the interface, or get rid of the interface entirely? This might be the better option.

I think fundamentally something is wrong with the implementation in that we are extending `ContainerBase` (which extends `Container`) which has an implementation of `transferStackInSlot`, and then also implementing an interface that has an identical method but is not related by inheritance.

**Comment by khazoda** [comment]
Glad you found the cause, I'm assuming all crafting blocks and items in cyclic extend that same method, as the portable crafting table also causes the same crash.

**Comment by trunksbomb** [comment]
Yes that's right.

In dev, I confirmed that my option 2 above fixed the crash but that's kind of a sketchy way to do it. I think we can just do away with the interface but I'll let the mod author decide.

**Comment by khazoda** [comment]
👍 that makes sense. Perhaps support for crafting tweaks could be added, as that mod adds the same type of functionality to the vanilla crafting table?

**Comment by Lothrazar** [comment]
yeah https://docs.oracle.com/javase/8/docs/api/java/lang/AbstractMethodError.html .  going with option 2 , differently named wrapper method to avoid the double abstract override. maybe its better to do option 3,  totally get rid of the interface, but thats way more work and might cause other issues.  unknown which mod causes this compatibility error, possibly a coremod or mixin, as error doesnt happen in standalone mod at all

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3154443
