### ISSUE TITLE
(1.16.4) Forester - not Consistent while Saplings/Trees.

### ISSUE THREAD

**Issue by Danekjovax** [PrinceOfAmber/Cyclic#1653]
Minecraft Version: 1.16.4

Forge Version: forge-1.16.4-35.1.13-universal

Mod Version:  Cyclic-1.16.4-0.10.1

Single Player or Server: Single Player

Modpack: Explorico 1.4 (https://www.curseforge.com/minecraft/modpacks/explorico-1-16-4)

Describe problem (what you were doing; what happened; what should have happened):
Placing a Forester in front of a pre-plotted area with planted saplings (tested with vanilla Oak saplings and Silent Gear mod Netherwood saplings from SilentGear-1.16.3-2.4.4+189-hotfix) results in the Forester working as expected during its first few scans where it will harvest any grown trees, but for unknown reason(s) it fails to harvest any other trees on subsequent scans. It will still place saplings (if it has some in its sapling slot in the UI).

Breaking and replacing the Forester allows it to harvest these trees, but only after the first scan pass the problem may reassert.

To note, the Forester was hooked to RF power and was properly set to Always On mode.

Video/images/gifs (direct upload or link): 
![2020-12-27_21 45 13](https://user-images.githubusercontent.com/10191173/103185988-cf91eb00-488c-11eb-8df1-4ed9dfeac255.png)
![2020-12-27_21 13 30](https://user-images.githubusercontent.com/10191173/103185992-d1f44500-488c-11eb-9494-59b222f5b685.png)

Thank you for your time, and for this great mod!

--- Danekjovax ;2)

**Comment by Danekjovax** [comment]
Updated OP.  Not specific to 2+ pass to "fail", as one run had run about 5 passes before failing.

**Comment by trunksbomb** [comment]
I assume you're talking about a Forester instead of a Harvester? Forester is for trees, Harvester is for crops. I see you've got both a Harvester and a Forester in your picture.

I'm 6 passes in on the latest version (your modpack is behind a couple versions) and can't replicate in Single Player with Oak Saplings. Update Cyclic yourself or ask the modpack author to update it and see if your problem persists. There's been a lot of work surrounding the Forester lately.

**Comment by Danekjovax** [comment]
Thank you for the quick response.  

In the pictures above I have a forester and an item collector, and yes I mistyped and mentioned Harvester.  OP is corrected now. 

I'll relay your suggestion.

**Comment by Danekjovax** [comment]
We tried the latest version suggested, but still observe the issue.  Let me know if you need more information.  Thanks.

**Comment by Lothrazar** [comment]
Looks like they fixed it in SilentGear-1.16.3-2.4.11+200.jar

The problem was that those red "logs" were not actually identified as #minecraft:logs , where now they are as seen in F3 on the right. so its running and chopping great now  
![2021-01-06_15 31 30](https://user-images.githubusercontent.com/621529/103832885-4de05100-5034-11eb-978f-48ee4d40b39e.png)
