### ISSUE TITLE
items not melting in Melting Chamber

### ISSUE THREAD

**Issue by toachronos** [PrinceOfAmber/Cyclic#1658]
Minecraft Version: 1.16.4

Forge Version: 35.1.13

Mod Version: 1.16.4-0.10.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Melting Chamber is receiving power, the texture "Glows" as if it should be working, but the test blocks (Magma cream, Magma block, Honey block, slime balls) are not being melted even after around 5-10 minutes of waiting.

**Comment by choekstr** [comment]
Typically the items need to occupy both slots to melt.  for instance, with magma blocks, 2 of them make 1000mb of magma.  you can't put 2 magma blocks in the first slot.  It MUST be 1 and 1, occupying both slots, for it to melt.  It's working fine for me in 1.16.4-1.0.0 (haven't tried yet in 1.0.2 version).

**Comment by Lothrazar** [comment]
@toachronos can you post a screenshot of your machine GUI with the recipe filled?  The recipe specifically shows three blocks filled, (this is on purpose since it would be unbalanced for one slime block to make the same fluid as 3)

![slime](https://user-images.githubusercontent.com/621529/103833474-f04d0400-5035-11eb-8f74-554e3c7b88fa.png)

**Comment by toachronos** [comment]
![image](https://user-images.githubusercontent.com/76840196/104069691-8c604200-51d3-11eb-8699-cf9c78fc3a70.png)
An attempt to  (Following the JEI recipe) melt two magma blocks into magma

**Comment by MichaelNZ404** [comment]
No issues on the latest version of cyclic for me.

https://user-images.githubusercontent.com/4734163/104560882-42270700-5692-11eb-8bcd-2f60a710dd30.mp4
