### ISSUE TITLE
Storage Bag deletes all content

### ISSUE THREAD

**Issue by oOMitchOo** [PrinceOfAmber/Cyclic#1659]
Minecraft Version: 1.16.4

Forge Version: 35.1.9

Mod Version: 1.16.4-1.0.1

Single Player or Server: Server

Describe problem:
I'm playing on a Server with the "Team Rustic" (v2.7) modpack. And I've put an item in my bag which caused the bag to delete all its content.

I'm not sure which item it was (I was exploring the world and putting dungeon loot into it) or if it was the combination of different items (the bag was quite full) and no, I definitely didn't put it in "hit deposit mode".

I wasn't yet able to recreate the bug, but I will try some things out tomorrow.

**Comment by Lothrazar** [comment]
Did you shift click the item in, or pick it up and place it in a slot?  Also are there other inventory mods installed such as mouse-tweaks or inventory tweaks?

Yeah let me know if you find anything else.

**Comment by oOMitchOo** [comment]
Those inventory mods are in the modpack:
- Inventory Tweaks Renewed by David1544
- Mouse Tweaks by YaLTeR

I'm pretty sure, that I shift-clicked them into the bag. I wasn't yet able to recreate the bug but I'll continue testing.

**Comment by oOMitchOo** [comment]
OK, it happened again.

I'm pretty sure it is because I changed my gamemode to creative (I'm building some structures in spawn for everyone).

The last time it happened I switched to creative too, because I had to fix something on the nether portal structure.

It doesn't happen everytime though. I'll test some more.

**Comment by oOMitchOo** [comment]
OK, I've replicated it:
1. Be on a server in creative mode.
2. Put some items into the storage bag.
3. Wait/do other stuff for about 1 min. (I think you have to do something which changes your player inventory though)
4. Open bag and it is empty.

The items doesn't disappear right away though. Don't know if that's a sync issue. It is definitely related to creative mode though.

**Comment by BlueAgent** [comment]
Likely due to https://github.com/MinecraftForge/MinecraftForge/issues/7359 since the [Storage Bag uses a capability for storing items](https://github.com/Lothrazar/Cyclic/blob/3c2ab7e0177dbf6347bca05c67aa9e5da26bff23/src/main/java/com/lothrazar/cyclic/item/storagebag/StorageBagItem.java#L222).

Summary is that in creative the client dictates the items in their inventory. Capability data is not synchronized from the client to the server. When you pick up an item with the mouse in creative it actually vanishes then gets spawned back in by the client when it is placed back down iirc.

A workaround is provided [here](https://github.com/MinecraftForge/MinecraftForge/issues/7359#issuecomment-755019439) by brandon3055 for when the capability has access to the item code.

**Comment by oOMitchOo** [comment]
I mean... if it is vanilla Minecraft behaviour then it's ok, I guess.

A warning on the storage bag (in red letters) would be nice though.

**Comment by Lothrazar** [comment]
Thanks for the updates and the links

**Comment by Lothrazar** [comment]
I added the fix mentioned, and it caused clients not being able to join servers due to the tag breaking packets. reverting the change and closing the issue, since its known to exist and is baked into the raw vanilla game and/or forge
