### ISSUE TITLE
[1.15.2][Mod Interaction] max health increases every time you die

### ISSUE THREAD

**Issue by ChakatStormCloud** [PrinceOfAmber/Cyclic#1703]
Minecraft Version: 1.15.2
Forge Version: 31.2.47

Mod Versions:
Cyclic 1.15.2-0.7.0
Minestuck 1.15.2-1.5.1.0

Single Player or Server: Both

Problem Description:
Minestuck has a leveling system that increases the players Max HP as they progress, up to 20 extra hearts.
It works correctly on it's own with the health increase remaining the same between deaths, but with cyclic installed, every time you die, the Max HP is increased by the current bonus, meaning after 20 or so deaths, even at a low level, you now have close to 100 HP.

Log file link:
no relevant logs or debug messages produced.

Link to the issue in the other mods github: https://github.com/mraof/Minestuck/issues/263

**Comment by ChakatStormCloud** [comment]
I'd imagine regardless of which mod needs to make code changes to fix this, someone is going to need to ask someone how they've got their system set up

**Comment by kirderf1** [comment]
The fault seems to be with cyclic's handling of the player clone event in [ItemEvents](https://github.com/Lothrazar/Cyclic/blob/trunk/1.15/src/main/java/com/lothrazar/cyclic/event/ItemEvents.java#L40), together with the max health attribute modifier handling in [UtilEntity](https://github.com/Lothrazar/Cyclic/blob/98a8644a2c6c059be4e22611df73cf12c752c633/src/main/java/com/lothrazar/cyclic/util/UtilEntity.java#L146).
I'd assume that the expected behavior is that the max health attribute modifier provided by cyclic gets copied over to the new player entity on clone.
The actual behavior is that on clone, it copies the effect of any max health modifiers which have not yet been copied over to the new player, and applies this effect to the new player entity as cyclic's own max health modifier. (That is assuming that other mods are only working with addition modifiers)

The solution would be to rework any values used for the cyclic max health modifer to not use the max health value with all modifiers applied (`entity.getAttribute(SharedMonsterAttributes.MAX_HEALTH).getValue()`).
Two alternatives are:
- Work with the modifier value directly. (define and use `setAddedMaxHealth(entity,amount)` instead of `setMaxHealth(entity,max)`)
- Work with max health with cyclic's modifier only/base value with cyclic's modifier value added to it (`entity.getAttribute(SharedMonsterAttributes.MAX_HEALTH).getBaseValue() + modifierValue`)

PS: After writing all that, I saw that the 1.16 version of the mod had already gotten this fixed through 4208a7a75d1cb66837e0550f38a8a483b43071ad.
