### ISSUE TITLE
Cyclic fans pushing botania mana pulses

### ISSUE THREAD

**Issue by cainamar** [PrinceOfAmber/Cyclic#1718]
Minecraft Version: 1.16.4 (dw20 pack)

Forge Version: 35.1.15

Mod Version: 1.0.1

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):

attempting to use cyclic's fans for a loonium-based mob farm and realized the mana spreaders' pulse trajectories were being changed by the fans, resulting in them not sending mana to the targeted pool

I'll be honest, I'm not sure if I should report this on botania's github too but it seems like it's more on cyclic's end

Video/images/gifs (direct upload or link): 

https://user-images.githubusercontent.com/53030836/105275170-afdca280-5b6c-11eb-9550-1e7af9077db3.mp4

**Comment by BlueAgent** [comment]
Botania's mana pulses are considered projectile entities.
The same thing happened with Blood Magic's Sigil of the Whirlwind back in 1.7.10 and [Astral Sorcery's Armara Ritual](https://github.com/HellFirePvP/AstralSorcery/issues/1195) in more recent versions.
Also, IIRC Botania's totally fine with their mana burst projectiles getting affected by other mods. It's intentional I rememeber reading somewhere.

**Comment by cainamar** [comment]
yeah that sounds like something botania would be ok with lol

I just switched to vector plates anyway, but if this is an intentional interaction I'll close it now
