### ISSUE TITLE
Crafting ungrinder BUG - Ininite resources.

### ISSUE THREAD

**Issue by Futi63** [PrinceOfAmber/Cyclic#1727]
Minecraft Version: 
1.16.4

Forge Version: 
35.1.37

Mod Version: 
Cyclic-1.16.5-1.1.4

Single Player or Server:
Server

Describe the problem (what you were doing; what happened; what should have happened):
uncrafting grinder ungrinds items indefinitely until broken, the item placed in the ungrinder should be consumed after 1 use, but this does not happen and you get infinite resources.

Video/images/gifs (direct upload or link): 

https://user-images.githubusercontent.com/34105472/105856214-e12bf700-5fe0-11eb-9d45-18e38e4ecd29.mp4

**Comment by BlueAgent** [comment]
This line [here](https://github.com/Lothrazar/Cyclic/blob/1f4b47c37cc26d30140377c7d661468707651ac5/src/main/java/com/lothrazar/cyclic/block/uncrafter/TileUncraft.java#L91) needs to be switched to use inputSlots.

Sorry, in one of my PRs I moved the cost payment to if the recipe was successful rather than just consuming if there's no non-container ingredient so after [switching to using the wrapper](https://github.com/Lothrazar/Cyclic/commit/6e77bc5c09e8106afd6c95397010cd2a2c6b0ed5#diff-114e85a755b5e21750d28bcacb9b2bb26eac926071023463487caf0a3ebada2fR51-R53) it prevented the input slot from being accessed directly through inventory wrapper.
