### ISSUE TITLE
Disenchanter does not remove enchantments from Tetra tools

### ISSUE THREAD

**Issue by cmcgowan27** [PrinceOfAmber/Cyclic#1737]
Minecraft Version: 1.16.4

Forge Version: 1.16.4-35.1.36

Mod Version: 1.16.5-1.1.4

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
When an enchanted Tetra tool is placed in the disenchanter, it creates an enchanted book with the enchantments, but does not remove the enchantments from the tool. Provides a near-effortless way to duplicate enchanted books.

Log file link:

Video/images/gifs (direct upload or link): 

![Cyclic_disenchanter_1](https://user-images.githubusercontent.com/20251174/106378558-dde39300-6373-11eb-96d4-10356486b830.JPG)

![Cyclic_disenchanter_2](https://user-images.githubusercontent.com/20251174/106378562-e20fb080-6373-11eb-998f-1a3471541d79.JPG)

**Comment by BlueAgent** [comment]
If you try put that pickaxe back into the disenchanter it doesn't give you a second Fortune III book from my testing.
I think the vanilla enchantments are hidden and Tetra seems to keep track of enchantments seperately or something.
Would probably be good to report this to Tetra devs since the same thing happens with Industrial Foregoing's Disenchanter too.
I think they may be able to give more insight into this.

![2021-01-31_17 17 13](https://user-images.githubusercontent.com/630920/106379639-45d3c100-63e8-11eb-9585-d29e1bed2e10.png)

**Comment by cmcgowan27** [comment]
Strange... I was able to do it multiple times. Anyway, thanks for the advice, I'll take it to Tetra. I never know who to report the bug to when it comes to these weird interactions between mods.
