### ISSUE TITLE
Miner mines itself

### ISSUE THREAD

**Issue by Dovencio** [PrinceOfAmber/Cyclic#1744]
Minecraft Version: Direwolf 20, 1.16.5

Forge Version: 36.0.14

Mod Version: 1.16.5-1.1.5

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

I placed down a miner and set the miner to mine an area. I turn it on by changing the redstone sensitivity and I give it a pickaxe (tetra) or a shovel (vanilla, iron). It just breaks itself.

Log file link:

Client: https://pastebin.com/XjGktUbq
Server pt1: https://pastebin.com/2CaUtfmU
Server pt2: https://pastebin.com/rTG8Racp
Server pt3: https://pastebin.com/ptCTgdNn

Video/images/gifs (direct upload or link): 

https://www.youtube.com/watch?v=4BCnWvmycJE

**Comment by Lothrazar** [comment]
Fixed in latest release :)

**Comment by ksc4130** [comment]
:-(((
The server I play must have the old version. My miner just went poof

**Comment by MrManiacc** [comment]
Can confirm this is broke in 1.2.7. The miner is still mining it's self on the latest release. No crash log, no problems, the pickaxe pops out, the miner just disappears into thin air.

**Comment by LoneStarrr** [comment]
Can also confirm this still happens in 1.2.7

**Comment by dpcollier128** [comment]
Also occurs in version 1.3.4 on All the Mods 6 Sky...

This occurs in the Other dimension (only dimension in the pack with usable land) and whether the miner is trying to mine within a claimed area or not. My individual issue is likely due to using a Tinkers Contruct pickaxe as opposed to any other kind. So far, pickaxes from Cyclic, Minecraft, or AllTheModium seem not to cause this issue at all.

Incidentally, the Cyclic Miner still fails to break Other ores... even when it wields an AllTheModium Alloy Pick. 🤷
