### ISSUE TITLE
[Feature request] GUI customization of face-slot correspondence in melting and solidifying chambers

### ISSUE THREAD

**Issue by AbacusOperator** [PrinceOfAmber/Cyclic#1763]
Currently melting and solidification chambers don't have any GUI that would allow to customize correspondence between input and output slots of melting and solidification chamber and faces of those chambers as blocks. This makes automation with hoppers impossible.

**Comment by Lothrazar** [comment]
this probably was changed/fixed since feb.

Currently: Hoppers and cables do not pull out of the left three slots, only the output of solidifiers.  so automation = easy. nothing pulls out the recipe

For melter: the output is a liquid.  so you will never need to extract items from there at all, so hoppers and item extractors wont be used.  Pump in items, pump out liquid = done. automation = easy again

So yeah, maybe it was busted before but seems great now.

(also doing something weird like locking North face to slot 0, south to slot 1, Down to slot 2, that just seems like a terrible player experience.  I rarely see mods doing this, mekanism used to)

**Comment by sisby-folk** [comment]
Re-Digging this one up to point out an oddity that this may be referring to.
![image](https://user-images.githubusercontent.com/55819817/165057366-cfb1821f-c9a7-4252-bee1-417e2e83e647.png)
Is there any way to automate this recipe?

If not (assuming the recipe isn't default) what would be a recommended alternate recipe?

Having inputs for eggs and wheat just causes the machine to fill up with whichever can be supplied faster, at random.
There seems to be no way to "select" a recipe and have the slots fill correctly as there might be with say, a thermal sequential fabricator.

![image](https://user-images.githubusercontent.com/55819817/165057942-1ed55e87-f741-4c54-8eeb-f123a83bdca6.png)

The only solution to this I can see is to _guarantee_ that the solidification chamber runs slower than the production machines
