### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by benbenlaw** [PrinceOfAmber/Cyclic#1771]
Minecraft Version: 1.16.5

Forge Version: 36.0.39 and 36.0.45

Mod Version: 1.1.6

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):

Able to duplicate any item in the game by "You just have to have a full inventory, and one stack of the item you want to dupe in your inventory and another at your feet. Q the items out of your inventory and it duplicates them"

https://user-images.githubusercontent.com/42780877/109137615-4a726780-7751-11eb-9569-5c33d393b076.mp4

also its not a storage drawers bug as i was able to replicate with only cyclic installed

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Kimochii-x3** [comment]
From my testing forge version doesn't matter.
First occurance of this bug is in Cyclic-1.16.4-1.1.2 for mc 1.16.4 released Jan 14th 2021
All other cyclic versions prior don't have that bug occuring, this is definitely cyclic only, tested item variety taking up slots in the inventory.
You can dupe any stackable item and on the ground you need at rare occasions just 3 items while you have 1 stack of them in your inv to dupe, sometimes you might need more than 3 so 4 or 5, 5 would be the bare minimum to make it work 100% of the time.
Tested item position in inventory, seems like it doesn't matter just anywhere you can spam or hold Q to drop the item works.
Hope my testing helps narrowing down the cause of this dupe bug as its quite absurdly OP lol.
