### ISSUE TITLE
loot drop rates

### ISSUE THREAD

**Issue by prodigyrick** [PrinceOfAmber/Cyclic#1861]
Minecraft Version: 
1.16.5

Forge Version: 
forge-1.16.5-36.1.31

Mod Version: 
Cyclic-1.16.5-1.2.11

Single Player or Server:
Server

Describe problem (what you were doing; what happened; what should have happened):
Drop rates are miniscule compared to previous versions (1.12.2) and you can hardly see them anywhere.
The building of these object recipes are ridiculously hard or near impossible for most but endgame making it useless throughout most of gameplay.

Log file link:
N/A

Video/images/gifs (direct upload or link): 
N/A

**Comment by Lothrazar** [comment]
Drop rates of what? exactly?    Which item or block are you talking about.  

This mod doesnt add any mob drops. and  1.14+ it doesnt edit any chest loot tables since it makes more sense to leave that up to modpacks/datapacks.

But then you say "object recipes". which recipe? i dont have any blocks named "object". im very confused
