### ISSUE TITLE
Game crashes when i have cyclic enabled, disabling it fixed the issue, but i'd like to have it in my modpack

### ISSUE THREAD

**Issue by Walparr** [PrinceOfAmber/Cyclic#1868]
Minecraft Version: 1.16.5

Forge Version: 36.1.32

Mod Version: 1.3.1

Single Player or Server: Neither (didnt boot to menu)

Describe problem (what you were doing; what happened; what should have happened): Game crashes on boot, doesnt get to the main menu

Log file link: https://gist.github.com/Walparr/99bcc7e919b1584962101956f0fe1d79

Video/images/gifs (direct upload or link): 
![Capture](https://user-images.githubusercontent.com/87207333/125130372-89ee8e80-e109-11eb-9b6e-0830ef5c6c9f.PNG)
![Capture2](https://user-images.githubusercontent.com/87207333/125130375-8a872500-e109-11eb-8b45-846a183decdc.PNG)

**Comment by Lothrazar** [comment]
if you uninstall the hplus-forge-2.0.0.jar                             |HopperPlus                    |hplus       (hopper + , better-hoppers whatever their name is now) the game will run again.

Basically their mod, instead of adding a new block for their hopper, went in and broke everything to do with vanilla hoppers, which means its incompatible with a bunch of stuff.  

Something like this might be a good replacement, adds a new block thats an upper https://www.curseforge.com/minecraft/mc-mods/uppers

**Comment by Lothrazar** [comment]
ill add a patch to try to stop the crash in 1.3.2, but still might not be fully compatible
