### ISSUE TITLE
[1.16.5] Block State card has trouble with leaves

### ISSUE THREAD

**Issue by Column01** [PrinceOfAmber/Cyclic#1880]
Minecraft Version: 1.16.5

Forge Version: 36.1.65

Mod Version: 1.3.3

Single Player or Server: Forge Server (haven't tested in SP)

Describe problem (what you were doing; what happened; what should have happened):
When using a miner to break down some trees (I need the leaves for other things) the block state card has trouble with leaves. Some leaves are destroyed but others are not. Is there some way to make a fuzzy block state for the miner to break all blocks of that type regardless of state?

Log file link: N/A

Video/images/gifs (direct upload or link): N/A

**Comment by Lothrazar** [comment]
hmm, oh yeah. since its matching the state exactly on every property. which is good for stuff like Stairs and slabs.  but for a lot of use cases including leaves, you want it to "Match on the block , and ignore all the details". leaves storing stuff like snowy:true and false, distance, it knows to be persistent: if placed by a player etc .

So i need to put in some sort of toggle or setting on the data card...

**Comment by Column01** [comment]
Why not make another card based on the block state card with a recipe derived from it using a block of wool to make it a "fuzzy" Block state card. Instead of matching the block state exactly, it matches the block material when placed in the miner
