### ISSUE TITLE
Storage bag deletes items upon going into creative on server.

### ISSUE THREAD

**Issue by Darkmega18** [PrinceOfAmber/Cyclic#1886]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.2.2

**Mod Version:** Cyclic-1.16.5-1.3.4.jar

**Single Player or Server:** Server only. 

**Describe problem:**
Seems to be:
whenever I enter curio menu, while having a storage bag, the storage bag deletes all items within itself.
It is fine in survival, and creative as long as you don't go into creative. I found it by accident when testing some curio stuff on the server that was happening. :V

**Log file link:**
Nothing in logs about bugs.

**Video/images/gifs (direct upload or link):** 
_Excuse my friends in the background also playing on the server that I'm talking with while testing, and a bit of fluffy language when I couldn't figure it out just before I figured it out._
https://user-images.githubusercontent.com/8104689/127734812-cd2b7e04-5b1d-42ad-8c80-fa3834abbf4e.mp4

related to curios it seems. curios version is:
curios-forge-1.16.5-4.0.5.2.jar

**Comment by Lothrazar** [comment]
I know its been a while, but this bug is avoided by never going into creative mode. caused by vanila client logic.

However there might be a workaround i can add https://github.com/Flanks255/simplybackpacks/blob/master/src/main/java/com/flanks255/simplybackpacks/items/ItemBackpackBase.java#L144-L155

**Comment by Darkmega18** [comment]
> I know its been a while, but this bug is avoided by never going into creative mode.

![image](https://user-images.githubusercontent.com/8104689/138574713-9dbde2e7-6a81-41e8-b5b2-594583f10704.png)

but it's a lot harder when you need to test a modpack with friends and stuff goes wrong.

Do what you can. Sophisticated backpacks and most other storage mediums I've tried in my pack don't have such issues. So I'm really not sure why yours does.

**Comment by Lothrazar** [comment]
Closed as cannot replicate and stale. does not affect creative players.  1.19+ item containers are getting remade anyway

**Comment by Faylen** [comment]
I'm actually going to bump this because I'm playing in 1.19.2, mod version 1.8.2 and I've had my items completely disappear.
Private modpack with friends, tped to cords to see if it's a server problem or client problem making my friend unable to connect and switched the z and y, putting me in the void.
I went into creative to not die, and only now after a lot of work happened on the server (therefore using a backup is pointless, I'm not going to make their progress invalid) I noticed it deleted the items as it did it again. I then started trying to find issues regarding this, and found this thread

**Comment by Darkmega18** [comment]
got em.

**Comment by emmesbe** [comment]
> I'm actually going to bump this because I'm playing in 1.19.2, mod version 1.8.2 and I've had my items completely disappear. Private modpack with friends.

i, too, am using the same exact MC version and mod version.  while switching to creative, i too lost the contents of my Bag of Holding.  this doesn't effect my son, who is the host.

i believe i will just stay out of creative mode lol!  OR, try putting the bag in something, then go into creative- if i absolutely must. it's because my son is absolutely CRAZY, with his surprise massive "mob battles".. it's like an automatic response, go into creative lol

thanks for helping me find this post, i'll follow it, just in case "the powers that be" (the mods and the game), will play nice together and decide to not kill the contents!  i will say though, this does NOT happen in all versions of minecraft/cyclic, so i know it's one of those "things" that is most likely out of loth's hands.

**Comment by Darkmega18** [comment]
Hrm... sounds like I might need to do some of the old binary search testing at some point... *sigh*
