### ISSUE TITLE
Balance magic bean 

### ISSUE THREAD

**Issue by leglerm** [PrinceOfAmber/Cyclic#189]
Version 1.8.13

First issue is that magic beans can replicate themselves using the right click harvest function that some mods add. So whenever i right click the plant i keep the plant and get an extra magic bean. This doesnt happen with the cyclic harvesters.

Second issue is the balance within it. From my point of view all items have equal chances. I have my cyclic farm running for around 2-3 days on a 11x11 field. I have 130 netherstars laying around. Even without the bean dupe above the initial costs are fairly low.. 

I would suggest if it is possible to balance drop rates within the magic bean harvest. Let us get more clay/glass but less of valuable items such as nether stars/ghast tears. Or add a config to disable certain drops from the magic bean.

**Comment by PrinceOfAmber** [comment]
" the right click harvest function that some mods add." is this the one from harvestcraft, or a different standalone one?  I know there are a few.  By default, the bean gives you a seed item and the regular drops if broken normally so you can replant it.

The harvester tries to be smart about it and it looks up the seed item for the plant and removes one of those from the drops before replanting, so that part in particular might be a bug with the right click harvest mod.

You are correct, all items currently have equal chance.  I should add config file for the dropped items.  Now that I think of it, this would also allow for items from other mods to be dropped.

Another thing i can add to config is whether bonemeal affects them.  For a long time i had this disabled, but i allowed bonemeal by request.  This again makes it a bit OP so that should be a config toggle
