### ISSUE TITLE
Uncrafting Grinder Disallow Lists Not Functioning

### ISSUE THREAD

**Issue by Darkosto** [PrinceOfAmber/Cyclic#1934]
Minecraft Version: 1.16.5

Forge Version: 36.2.8

Mod Version: 1.5.3

Single Player or Server: SMP & SSP

Describe problem (what you were doing; what happened; what should have happened): 

The first list to disallow recipe item outputs for the uncrafting grinder does not seem to function. I was able to out sticks and anything else I had in the config.

**Comment by Lothrazar** [comment]
When i set 

	ignore_list = ["minecraft:stick",
		Then i cannot uncraft sticks into their component ingredients. this seems to work 
a stack of ladders will still uncraft into sticks, this works as intended. since sticks are only the ingredients, and ladders are not on the ignore list
![stick](https://user-images.githubusercontent.com/621529/137825960-0cd16382-6df4-4500-a3e6-f5ae53c979a6.png)


If i add to the 

ignore_recipes = [  "forcecraft:transmutation*"

This value disables things like uncrafting raw meat to a force rod

There are no configs that look at recipe inputs, that is, theres no way currently to say "stick" and have it block all recipes with sticks as ingredients such as ladders

I will clarify text around the config file, add some defaults, and do more testing around the NBT checking flag. nbt_ignored = false as default does make sense
