### ISSUE TITLE
[1.18.1] Fluids not rendering in tanks nor buckets

### ISSUE THREAD

**Issue by DefiantEmer** [PrinceOfAmber/Cyclic#2074]
Minecraft Version: 1.18.1

Forge Version: 39.1.2

Mod Version: 1.6.15

Single Player

Cyclic fluids do not render in tanks nor in bucket items. They are also not rendered in JEI (Version 9.4.1.112). Tested with only Cyclic and JEI mods installed. Worked fine with 1.6.14 in same setup.

![1 6 15 Error](https://user-images.githubusercontent.com/101599466/158255837-5057d160-226f-4ac1-88f3-f179a2701fd9.png)

![1 6 14 Okay](https://user-images.githubusercontent.com/101599466/158255893-b476c43f-6b0a-48a1-a58f-700da1731f13.png)

**Comment by Lothrazar** [comment]
yeah its either a bug in forge or Mojang changed something, looking into it

**Comment by Lothrazar** [comment]
Aha.  So in 1.16 i could set a color on a fluid , for example 0x1234FF for red, since its RGB.

But in 1.18 that now has a transparency value, and the default is zero, so everythings invisible since my numbers became 0x1234FF00 .  Fix coming out soon
![fix](https://user-images.githubusercontent.com/621529/158743680-ff21ccc9-4ab2-4c4a-967e-4389b5a05baa.png)
