### ISSUE TITLE
Ender Library Dupe Glitch on 1.12.2

### ISSUE THREAD

**Issue by ChrisJacobsJr** [PrinceOfAmber/Cyclic#2075]
Minecraft Version: 1.12.2 Stoneblock

Forge Version: 14.23.5.2854

Mod Version: 1.20.2

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):

Place ender bookshelves and ender libraries as so: 
XXOXX
X is ender bookshelves, O is ender library.
right click the ender library with an enchanted book. 

What happened: Book is duplicated 
What should have happened: Book is placed inside of ender bookshelf. 

Log file link: n/a

Video/images/gifs (direct upload or link): 
https://youtu.be/hC8O80KAk7o

**Comment by Lothrazar** [comment]
i saw whats happening in your video, but whenever i try the setup, it just gives me an empty book. even if my book has 2 enchantments. probably because your on an old mod version, works as intended in 1.20.11
![2075 bbb](https://user-images.githubusercontent.com/621529/160312367-736828dd-79a4-4b00-824b-7e8de4de889e.gif)
