### ISSUE TITLE
Automatic Fishing Net works with any item

### ISSUE THREAD

**Issue by Kisox** [PrinceOfAmber/Cyclic#209]
I tried the Automatic Fishing Net on HermitPack version 1.5.1.
The mod has the version 1.8.13

I tried to use EnderIO item conduits with the Automatic Fishing Net and as i played around with it i realized that the item slot for the fishing rod was actually filled with fish.
The next idea i had was working perfectly. A simple cobblestone generator now helps me with keeping the fishing 24/7.

**Comment by PrinceOfAmber** [comment]
Weird, yeah it should allow only fishing rods in that slot.  Somehow conduits are getting around that testing step to verify its an item.  Thanks for reporting it.  Possibly a bug in enderIO as well, where they arent testing isValidForSlot(item).  Also, bug in cyclic since it currently says "great its filled, dont test if its a fishing rod or cobble."

**Comment by PrinceOfAmber** [comment]
Fixed in 1.9.4.  Keep the reports coming :) https://minecraft.curseforge.com/projects/cyclic/files/2358564
