### ISSUE TITLE
possible bug, or just not implemented. auto user and tinkers weapons.

### ISSUE THREAD

**Issue by MarkSzita** [PrinceOfAmber/Cyclic#216]
The automated user doesn't recognize tinkers weapons as weapons and instead just does punch damage.

**Comment by PrinceOfAmber** [comment]
yeah i do see this happening. WIth a tinkers Firewoord Broadsdword i can kill a creeper in 3-4 hits, it takes more than double that. 

Not sure why this happens , since im just calling     fakePlayer.get().attackTargetEntityWithCurrentItem(ent);

im going to try some alternate methods such as http://www.minecraftforge.net/forum/index.php?topic=43152.0

**Comment by PrinceOfAmber** [comment]
Fix coming out soon. now a Manulyn broadsword in the user kills a creeper in 2 hits.  This also fixes enchantments such as sharpness being ignored.  Also tested with enderio sword.

**Comment by PrinceOfAmber** [comment]
Fixed in 1.9.8  https://minecraft.curseforge.com/projects/cyclic/files/2361405
