### ISSUE TITLE
ticking block entity with fluid pipe

### ISSUE THREAD

**Issue by Gugus5651** [PrinceOfAmber/Cyclic#2161]
Minecraft Version: 1.16.5

Forge Version: 36.2.22

Mod Version: Cyclic-1.16.5-1.5.18

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
First of all, I’m sorry about my English. I was on my Minecraft world (mod pack: chroma technology 2), I wanted to connect the "Garden Cloche" (Immersive engineering) and the sink (cooking for blockheads) with a fluid pipe (Cyclic) and when I made a right click on the fluid pipe with a wrench, the game closes.
I really hope someone can help me.

Log file link: https://pastebin.com/mJXBJZwj

**Comment by Gugus5651** [comment]
Hello, sorry for my English, I came to test an old version of Cyclic( 1.16.5-1.3.4) and I have no more crashes! It’s really weird, how does it feel?

**Comment by Lothrazar** [comment]
This is my code referenced in the log https://github.com/Lothrazar/Cyclic/blob/trunk/1.16/src/main/java/com/lothrazar/cyclic/util/UtilFluid.java#L154
i think this bug is on the side of 'immersiveengineering', it seems like a cloche is giving an error of "java.lang.ClassCastException: net.minecraft.client.multiplayer.ClientChunkProvider cannot be cast to net.minecraft.world.server.ServerChunkProvider"

**Comment by Lothrazar** [comment]
As listed above, bug is coming from immersive 

`	at blusunrize.immersiveengineering.common.blocks.metal.ClocheTileEntity.sendSyncPacket(ClocheTileEntity.java:295) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.blocks.metal.ClocheTileEntity$1.onContentsChanged(ClocheTileEntity.java:101) ~[?:?] {re:classloading}`
