### ISSUE TITLE
[Question] Enchants in the config have similar/shorter names than in-game

### ISSUE THREAD

**Issue by INooBTooMuch** [PrinceOfAmber/Cyclic#2173]
Minecraft Version: 1.18.2

Forge Version: 40.1.80

Mod Version: 1.7.8

In the configs (cyclic.toml) there are some names for enchants that are changed in game and also some I can't find.

multishot : its a vanilla one for crossbows, maybe meant multy_bow
launch : is multy-jump in-game
I cant find what "curse" is
step : is step-height
steady : is steady body in-game
beekeeper : beekeeping in-game

**Comment by INooBTooMuch** [comment]
Also the items have different names and is slightly inconvenient when trying to search with crtl+f.

**Comment by Lothrazar** [comment]
Updated this.  but i can only change the comments by the configs to not break anything. for example curse enchant will still be curse but comment will say 

(Gloom) Set false to disable enchantment

still have to keep the ids since ppl play in different languages and the /enchant command knows these.

I really should change the ID of the curse enchant to "gloom" but i cant without breaking ppls items/worlds.
