### ISSUE TITLE
Latest 1.18.2 versions break modpacks ( 1.7.2 - 1.7.9 ) ( lag / BlockSpawnEvents mob spawns )

### ISSUE THREAD

**Issue by itsdinkd** [PrinceOfAmber/Cyclic#2187]
Minecraft Version: 1.18.2

Forge Version: 40.1.80

Mod Version: Cyclic-1.18.2-1.7.9

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):

Updated my modpack, another quality modpack 3 with the latest version of Cyclic. I upgraded from 1.7.2

After updating, as well as other mods, and 20 hours later of debugging, it has been discovered that Cyclic caused major issues where ticks would freeze in newly generated worlds. It doesn't happen 1:1. Sometimes it occurs right after creating and joining the world, other times it happens when exploring Overworld or end or nether. There isn't a definitive reason on how it starts. All region files it occurs on doesn't have a pattern. 

**The logs do not tell anything, neither latest nor debug.** This all came down to updating batches of mods, finding the batch where it started to occur in after many hours of trying to reproduce, and binary searching that batch. It ended up being Cyclic. 

Everything works fine on 1.7.2

**Comment by Lothrazar** [comment]
if possible do you have any logs or java snapshots or stuff from here https://www.curseforge.com/minecraft/mc-mods/spark to narrow this down?

Also im looking into different but also very similar issues actually, weve found that disabling these two following blocks doesnt disable some of its processing and also that reducing these numbers makes a huge impact on improving server tick time and resources. the version number makes sense also, as 1.7.3 was a big update (i probably should have called that 1.8.0 instead of 1.7.3 but regardless) it added tons of new stuff.

In config setting the following values low can help., for new versions such as 1.7.9. 

[cyclic.blocks.peace_candle] 
radius=1
height=1
[cyclic.blocks.no_soliciting]
radius=1
height=1

More changes are also in progress

**Comment by Lothrazar** [comment]
posting for reference from a different modpack dev which point to these areas https://spark.lucko.me/OASsHkpBKA
 
 
![unknown](https://user-images.githubusercontent.com/621529/196577514-759bcde5-18f2-486c-bb69-0c655e02bf08.png)

**Comment by itsdinkd** [comment]
I've tried spark initially when I was trying to discover which mod caused
it but it didn't run since there were no ticks occurring.

On my phone right now but aqm3 does change a lot of the config up, most
values were greatly lowered but I don't believe I set anything to 1:1

**Comment by GentlemanCheeseMan** [comment]
Yes! I had the exact same issue and I felt like I was losing my mind! Days and endless hours of troubleshooting. I don't have much to actually add unfortunately, but I can confirm this issue!

**Comment by Lothrazar** [comment]
my BlockSpawnEvents used to check dozens of blocks when a mob spawned which adds up with lots of blocks and lots of spawns together (event was looking for a block in the world).

now those blocks tick in a different way, and the cyclic spawn events dont have to get a bunch of blockstates all over the world 
1.18.2 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/4051593
1.19.2 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/4052462
