### ISSUE TITLE
Ore Prospector does nothing (1.19.2)

### ISSUE THREAD

**Issue by AeonicDread** [PrinceOfAmber/Cyclic#2190]
Minecraft Version: 1.19.2

Forge Version: 43.1.47

Mod Version: 1.7.12

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):
Using the ore prospector does nothing while my friends on the server have ores highlighted.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
This issue is stale and has long been fixed, but ill add info for anyone else looking back on it.

Ore prospector only detects blocks tagged with "#forge/ores" 
![forge ores](https://github.com/user-attachments/assets/c7ac32b6-4424-4e57-9be6-bfc37d5754cd)

Then it makes them visible while you are holding it 
![prospector](https://github.com/user-attachments/assets/9d5395a6-e323-47e1-82a2-dc40162f55f1)
