### ISSUE TITLE
crash at launch from "top.theillusivec4.colytra.common.integration.CyclicClientPlugin.onKeyInput" (1.18.2)

### ISSUE THREAD

**Issue by MoonMoonShark** [PrinceOfAmber/Cyclic#2196]
Minecraft Version: 1.18.2

Forge Version: 40.1.84

Mod Version: Cyclic-1.18.2-1.7.13.jar

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):

i'm not actually sure if this is a Colytra problem or a Cyclic problem, but the crash didn't appear until i updated Cyclic to the latest version. prior to this, i was able to start the game and enter the world, but once i updated, it crashes on launch, before ever getting to the main menu.

please let me know if there's anything i can do to help with this. thank you for everything! love your work!

Log file link:

[debug.log](https://github.com/Lothrazar/Cyclic/files/10003478/debug.log)

Video/images/gifs (direct upload or link):

**Comment by Mrbysco** [comment]
Cyclic probably changed some internals that Colytra used in their compat, this lies on Colytra, they'd have to update to fix the incompat

**Comment by MoonMoonShark** [comment]
okidoki! i'll pass this over to that github. thank you!

**Comment by Lothrazar** [comment]
i didnt know they had a plugin at all! hopefully its a small fix on their end

**Comment by Lothrazar** [comment]
if can make code changes to make plugins easier i am all ears.  (cyclic has no official api . closest thing would be this class but thats different and very specific https://github.com/Lothrazar/Cyclic/blob/trunk/1.18/src/main/java/com/lothrazar/cyclic/api/IHarvesterOverride.java )

**Comment by TheIllusiveC4** [comment]
This should be fixed now with the latest Colytra version. It was a trivial fix, just needed to update the package names in a few places.

> if can make code changes to make plugins easier i am all ears.

In Colytra's case, the integration is just for getting the Multi-Jump enchantment to work on chestplates with elytra attachments.

Currently, I need to mimic Cyclic's code while doing my own detection for a valid elytra attachment with the enchantment. It would be handy if there was a way to instead just tell Cyclic how to detect it in the first place and let Cyclic continue handling the rest of the logic on its own. Perhaps an event or something in or around this method:

https://github.com/Lothrazar/Cyclic/blob/b3dd9b8e32528188fcc65c55c5d34a290879c2ce/src/main/java/com/lothrazar/cyclic/enchant/MultiJumpEnchant.java#L115

So that developers could potentially inject their own ItemStack result if no others are found.

**Comment by MoonMoonShark** [comment]
team work makes the dream work! thank you all!!!!
