### ISSUE TITLE
An idea

### ISSUE THREAD

**Issue by llloyd4** [PrinceOfAmber/Cyclic#224]
So I was getting into the hearts, since Tinker's no longer has them. I noticed I can only have one more bar of health, gold. Now TC had 3, gold to blue then blue to green, was a royal pain getting to blue let alone green. So why not allow up to 3 over bars of health? :D

**Comment by PrinceOfAmber** [comment]
Actually this is already supported in the config file.  Its not in the config GUI, but if you look in the file you will see HeartContainerMax, so you can set that to 30.

**Comment by PrinceOfAmber** [comment]
Just double checked in my worlds, set that config value to 30 and i now have three rows of hearts.  

I dont know why your health bar is "gold", for me i get actual rows, you must have some other mod changing how the health looks

http://i.imgur.com/SPM7ru4.png .

Ill mark this as fixed by config. feel free to reopen or make a new issue for anything else.
