### ISSUE TITLE
Terra Preta not affecting modded crops

### ISSUE THREAD

**Issue by Jaden-Adonis** [PrinceOfAmber/Cyclic#2244]
Minecraft Version: 1.18.2

Forge Version: 40.2.0

Mod Version: 1.7.13 & 1.7.14

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Put 16 layers of terra preta under a farm
Only vanilla crops grow faster
Expected all crops to grow faster

If you think a log or pictures would help I can grab them, but I don't know if they would help any.

**Comment by Jaden-Adonis** [comment]
Actually, it seems like thermal series crops work, but pam's and mystical agriculture don't.

**Comment by Lothrazar** [comment]
this is by design, if checks if bonemeal can be used on the crops curent growth state, and if bonemeal cant be used then terra soil follows that same logic, and some modded crops disable this to block watering cans and other things.  mystical agrriculture if i remember always blocks bonemeal use.  (also terra soil it also checks if the block is a minecraft:crop or minecraft:sapling datatag )
