### ISSUE TITLE
[Config option request]

### ISSUE THREAD

**Issue by KingOfTheGamesYT** [PrinceOfAmber/Cyclic#2303]
Minecraft Version: 1.16.5

Forge Version: 1.16.5

Mod Version: Next version

I am making an update for a modpack rn and would like the option to completely disable the Emerald armor

**Comment by Lothrazar** [comment]
Hi. Sounds cool, i hope your modpack goes well.  

Most mods dont have ways to fully disable an item, because it isnt really needed.  Modpacks that ive made or played have many tools to disable or hide items.

One way is data packs, i made a quick data pack and tested it, this removes the Recipes for all the emrerald stuff using the forge:false condition
[cyclic_diable_stuff.zip](https://github.com/Lothrazar/Cyclic/files/12139831/cyclic_diable_stuff.zip)

(basically you can pull the recipe json out of the mod and add this one line in the json file
`  "conditions":[ { "type": "forge:false" } ],)`
(the downside of data packs is that by default they are used per world not per modpack but there are mods to fix this - they go into saves/worldname/datapacks/zip file here)


Alternately, CraftTweaker scripts can remove recipes
https://docs.blamejared.com/1.12/de/Vanilla/Recipes/Crafting/Recipes_Crafting_Table
Also the scripts can hide items from JEI 
https://docs.blamejared.com/1.12/en/Mods/JEI/JEI

**Comment by Lothrazar** [comment]
i havent tested them in ages but i used to have these example craft tweaker scripts  so they may or may not be useful examples https://github.com/Lothrazar/Cyclic/tree/trunk/1.16/crafttweaker

ref https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files?version=1.16.5

**Comment by KingOfTheGamesYT** [comment]
Thank you I will give these a try

**Comment by Fundryi** [comment]
I was looking for smth like that in the config, but on 1.20.1 it seems CraftTweaker doesn't support anything to "hide and remove" items in JEI etc, like you could just disable the recipes I guess, but then they are still visible :/ 

Why not have individual options for most/blocks/items :o
