### ISSUE TITLE
Bug: Game crashes when attempting to uncraft items from Applied Energistics 2

### ISSUE THREAD

**Issue by tlsctf2** [PrinceOfAmber/Cyclic#231]
Whenever I attempt to use the Uncrafting Grinder with items from Applied Energistics 2 in any way, even just scanning for a recipe, Minecraft crashes. I have only confirmed this glitch with the Certus Quartz Cutting Knife and Certus Quartz Fixtures, but the fact still stands that this does not happen with other mods I tried to do this with. These items use the standard crafting grid.

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this, i havent tried  AE 2 in 1.10 yet.

**Comment by PrinceOfAmber** [comment]
Can you let me know what version of Cyclic this issue happened in? There was a similar bug that was fixed in 1.9.4 here https://github.com/PrinceOfAmber/Cyclic/issues/208

Also, im running the latest build of both mods (downloaded and updated through curse client) now and it works for me http://i.imgur.com/VFBfYbW.png

**Comment by tlsctf2** [comment]
I'm using 1.9.3 at the moment. I'll try updating to see if that fixes it.

**Comment by PrinceOfAmber** [comment]
Sounds like it was the exact issue the 1.9.4 fixed 👍 .  Feel free to report anything else in the future.

**Comment by tlsctf2** [comment]
Fixed it, but not how I would have liked. See issue #248 for more.
