### ISSUE TITLE
Expanded Inventory Disappeared in a Crash

### ISSUE THREAD

**Issue by madalienist** [PrinceOfAmber/Cyclic#236]
My server crashed while in my regular inventory.  When I reloaded the game, my expanded inventory was gone.  I have backups, but would prefer to just restore the contents of the expanded inventory.  Can you tell me where the file is located.  I used NBT explorer to search the Player.dat file, but could not find it there (or i missed it).  

I can revert to a slightly older backup of the world, but will end up losing some builds. 

Thanks

**Comment by PrinceOfAmber** [comment]
I dont use player.dat, i use seperate files for this inventory.


Look for files that are (playername).invo   , that is the main inventory file. 

Also There should be a backup version that it tries to load when it hits an error, called (playername).backup,  .. however now that I think about it, there arent multiple backups, so if you loaded an saved a few times the backup may have been saved empty since it thought that was valid.

Do you any server logs or game logs from around the time it crashed, and also from when you loaded the game right after?   Im wondering if its similar to this other issue  https://github.com/PrinceOfAmber/Cyclic/issues/188

**Comment by PrinceOfAmber** [comment]
Did this happen only once and hten work normally after that, like a fluke? OR does this happen every time.  that is do you lose stuff every time in that invo

**Comment by PrinceOfAmber** [comment]
If this happens again  or you get a crash log, feel free to reopen this issue or make a new one. 

Ill have to assume the issue just happened because of the external server crash you mentioned.
