### ISSUE TITLE
flib doesn't mentioned as required dependency or in mod description

### ISSUE THREAD

**Issue by uhloin** [PrinceOfAmber/Cyclic#2396]
Minecraft Version: 1.20.1

Forge Version: 47.1.100

Mod Version: Cyclic-1.20.1-1.12.7.jar

Single Player or Server: single

Describe problem (what you were doing; what happened; what should have happened):
Just start game, get error about flib

Log file link:

[06Apr2024 12:12:23.369] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'flib', Requested by: 'cyclic', Expected range: '[0.0.10,)', Actual version: '[MISSING]'

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Yes this is a good idea. its marked so that most mod apps like GD launcher and curseforge launcher should auto install both, but just now i did add a section on the curseforge page to explain this and have a link. new "Required Dependencies" section   https://www.curseforge.com/minecraft/mc-mods/cyclic
