### ISSUE TITLE
[Functionality] Diamond and Magma Anvil

### ISSUE THREAD

**Issue by ryaninos** [PrinceOfAmber/Cyclic#2405]
Minecraft Version: 1.16.5

Describe problem (what you were doing; what happened; what should have happened):

Is there a config/or way to make tinker's tools repairable with the diamond and magma anvil? I saw the conversation talked about for Cyclic 1.12 online but wanted to resurface for 1.16.5.

For reference: I am a pack maker interested in making the tinkers tools repairable in the cyclic anvils.

Thanks,
Ryan

**Comment by Lothrazar** [comment]
tinkers tools hardcodes their items so that "isRepairable()" is false, which is checked here  https://github.com/Lothrazar/Cyclic/blob/5b2e076b3f19556c08ebc7ba889ff4bc13f7cb85/src/main/java/com/lothrazar/cyclic/block/anvil/TileAnvilAuto.java#L132  , the last time i checked.  so basically this means tinkers blocks it from there end 

By default the anvil tries to repair any item that has durability (except the ones in this datatag https://github.com/Lothrazar/Cyclic/blob/trunk/1.16/src/main/resources/data/cyclic/tags/items/anvil_immune.json ). 

so items with durability, that are not in that tag, that return true for 'isRepairable()' can be worked on
