### ISSUE TITLE
1.11.2 There's no End Gold Ore

### ISSUE THREAD

**Issue by DeadPigman17** [PrinceOfAmber/Cyclic#278]

**Comment by PrinceOfAmber** [comment]
Yes... this was a design choice.  Also nether has no Redstone Ore at all, and neither dimension has Iron ore.

for one, those colours would be hard to see (yellow gold on endstone texture / redstone on netherrack)

For two, its thematic - it makes sense for tons of gold to be in nether since the pigmen have some.  

Several times i have thought about adding these, but keep them super rare like in the 1% range.  Should i add these two? should i go further and add iron? maybe.  I guess since all ores are fully in config file i could - this was a recent addition.

**Comment by PrinceOfAmber** [comment]
Made a poll about it https://twitter.com/lothrazar/status/835893163818536960

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2387853 for 1.10

1.11 coming soon

**Comment by PrinceOfAmber** [comment]
1.11.2 https://minecraft.curseforge.com/projects/cyclic/files/2388149
