### ISSUE TITLE
If you change the type of your horse with emerald carrot to zombie or skeleton...(see desc.)

### ISSUE THREAD

**Issue by DeadPigman17** [PrinceOfAmber/Cyclic#304]
...you can't ride that zombie or skeleton horse unless you transform it back to a normal horse.

**Comment by PrinceOfAmber** [comment]
Are you in 1.10 or 1.11?

If its tamed before you change it , it should stay tamed. ..... however in 1.11 minecraft changed how all the horses work so i have to kill and respawn since its impossible to change entity type.  I thought I remembered being able to tame zombie/skeleton horses but ill have to check it out

**Comment by PrinceOfAmber** [comment]
The solution will have to be a new item that force-tames the horse even if its zombie or skeleton for 1.11.2

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2393324
