### ISSUE TITLE
about the inventory/crafting upgrades.

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#320]
you know when you're playing in a mod pack sometimes(for me is most of the times) you don't have hotkeys for the shortkuts, so I know is hard but you can make the crafting upgrade be the vanilla inventory ? (is like you gonna change the vanilla inventory for the crafting upgraded one).
 
I tink that you need just to change the vanilla inventory for the crafting upgraded one this will be realy useful because when I craft or get those upgrades I just don't use them, because they just don't are pratical.

**Comment by ulkunderscore** [comment]
You can do this yourself by changing the crafting upgrade to open with "E" and unbind the vanilla inventory.
However, I'm pretty sure this can cause incompatiblities with Inventory mods that are made for the Vanilla GUI.

**Comment by O-Barbaro-Desenhista** [comment]
yep its that why I'm saing that he coud change the vanilla for the crafting one. (I have alot of mods ho needs the vanilla interface.

**Comment by PrinceOfAmber** [comment]
It used to change the vanilla crafting one.   Actually it used to be a seperate standalone mod that just did this automatically, without the food.  https://github.com/LothrazarMinecraftMods/InventoryCrafting

The problem is that this is different than just adding a button on top of the screen, its literally removing and adding a new screen.  Since the inventory slots and graphics are all private and internal to the screen i cant just edit it gracefully, but floating above the screen is easy.  

So When i did have this, the game would crash when other things like balkins weapons mod or baubles or quark looks at the player and says "give me the players inventory screen, i know its one of these so do stuff with it.

If Forge had a way to support this, and i could do it without conflicting other mods, then i would love to.  

What I usually do is have the crafting and inventory screens bound to C and shift-C so i dont have to click the buttons.  https://github.com/PrinceOfAmber/Cyclic/issues/47
