### ISSUE TITLE
[Feature Request]Scepter version of the Structure builder.

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#322]
make a scepter version of the structure builder.
this septer will be like a block exchange but with a inventory and a pre configured pattern, just tink on the posibilites so much use for this thing.

**Comment by PrinceOfAmber** [comment]
I'm trying to think of how this would work.  The reason the builder places blocks one by one instead of all-at-once is to stop lag from doing that bulk action.

But then stuff like the Builders Wands mod does i fine, as does Schematica.  SO this might work .  But i would have to get a really solid Preview mode running otherwise mistakes would be bad

**Comment by PrinceOfAmber** [comment]
Well, i couldnt figure out any useful new way to make something like this, so i guess ill close the issue.

All these other projects are great for building tools
https://minecraft.curseforge.com/projects/better-builders-wands
https://minecraft.curseforge.com/projects/building-gadgets
https://minecraft.curseforge.com/projects/similsax-transtructors
https://minecraft.curseforge.com/projects/linear
