### ISSUE TITLE
Uncraft machine bug: industrial craft recipes dont reverse

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [PrinceOfAmber/Cyclic#330]
you can't uncraft the recipes from industrial craft (I don't know if is all of them or not but I tested a lot of items and none of them worked).

**Comment by PrinceOfAmber** [comment]
Yeah i havent added support for non vanilla recipes, the '?' button usually gives a bit of info.  Might come in future.

**Comment by PrinceOfAmber** [comment]
The uncrafter will never do non vanilla recipes, simply due to the limitations of forge.  They have coded the IRecipe interface to not output ingrediends.

 HOWEVER i am considering some new upgraded uncrafter block, some sort of Grinder/Crusher.  It will work totally differently, instead of looking up recipe ingredients, it would instead have its own recipes created for vanilla blocks, and maybe some mods as well, and then useing CraftTweaker you could add more.

Closing the issue for this reason.
