### ISSUE TITLE
Cyclic and Apricorn Plants from Pixelmon.

### ISSUE THREAD

**Issue by xTrickShotProx** [PrinceOfAmber/Cyclic#353]
While trying to use the harvester to get apricorns. The Harvester just breaks the plant. If you use the Automatic user. It harvests the plant but the item disappears. Version of Minecraft is 1.10.2.

**Comment by PrinceOfAmber** [comment]
Is this the right place to get the mod? Version 5.0.4? http://pixelmonmod.com/downloads.php

**Comment by PrinceOfAmber** [comment]
How do i plant apricorns? I tried using "Green Apricorn" on farmland and did nothing. Tried planting some berries too.


i did not see any seeds or saplings items either.

**Comment by xTrickShotProx** [comment]
Pixelmon version is 5.0.3. You plant Apricorns on grass. Berries are held by pokemon and not planted.

**Comment by PrinceOfAmber** [comment]
Thanks

**Comment by PrinceOfAmber** [comment]
Looked into it a tiny bit. So when I harvest the fully bonemealed grown apricorn , with an axe for example. i just get a log.  Which is the same thing the harvester is doing.

But i see what you mean because just right clicking the plant drops that apricorn item we want.  Re-labelling from bug to compatibility-suggestion , looking into it

**Comment by PrinceOfAmber** [comment]
closed: No new features are coming to 1.10, i just dont have the time. also pixelmon seems to have been killed
