### ISSUE TITLE
Mattock breaks bedrock

### ISSUE THREAD

**Issue by OrdinatorStouff** [PrinceOfAmber/Cyclic#385]
The 3x3 mattock can break bedrock as long as bedrock is not the block the break is targeting (if it's in the 3x3 aoe area the bedrock is destroyed).

Also works in the nether to make a hole in the ceiling as big as you'd like.

**Comment by PrinceOfAmber** [comment]
Yes I saw this recently, what version of the mod do you have?  It should be fixed in the latest updates 

https://minecraft.curseforge.com/projects/cyclic/files/2423197 for 1.10 and

https://minecraft.curseforge.com/projects/cyclic/files/2423204 or newer for 1.11

Now, if it still happens in the latest version of course i will check again.

**Comment by OrdinatorStouff** [comment]
Our modpack just updated (ATM1) and now has Cyclic 1.10.2-1.10.24

And yes, looks like this had already just been fixed, Thank you!
