### ISSUE TITLE
Compatibility with tools that use RF instead of durability [old: Cyclic Automatic Fishing Net and Redstone Arsenal]

### ISSUE THREAD

**Issue by llloyd4** [PrinceOfAmber/Cyclic#388]
Right. So. I put a Flux-Infused Fishing Rod into the Automatic Fishing Net and it *eats* the rod, literally. It catches a fish then the rod vanishes completely. O.o 

This is Cyclic 1.10.2 - 1.10.22 ...

**Comment by PrinceOfAmber** [comment]
Wat mod is this item from?

Most fishing rods go down one durability when you use them.  What happens when you use this one outside the machine? I assume it is unbreakable or somehow consumes some other resource?

The Automatic Fishing Net currently doesnt understand RF power if thats what it is charged with, it would be a nice upgrade though.

**Comment by llloyd4** [comment]
As I said in the title, Redstone Arsenal, and yeah, it's a RF powered fishing rod. Which is why I was using it, was going to set up a pull / charge / put back setup like Direwolf20 is doing for his beheader sword.

**Comment by fluid-uu-matter** [comment]
The tools from the Redstone Arsenal in then versions for MC1.10.2 has no metadata for damage. They use NBT data instead of metadata. Different form IC2 Electiric tools.

**Comment by PrinceOfAmber** [comment]
Thanks for information everyone.  In current 1.10 builds in my testing, it does not eat the rod anymore at least, which is a good thing.  

I am changing this from a bug to a feature request: that feature being "working with RF tooks and drain RF instead of durability". 

This feature could apply also to other tools using RF such as auto user, controlled miner, etc.  

I am no longer adding new features to 1.10, but all the Thermal mods are in 1.12 now.

**Comment by JaRyCu** [comment]
It looks like this bug still hasn't been fixed.  I'm playing All the Mods 3 for Minecraft 1.12 and just experienced the same "bug" as the OP.  I made the RF Fishing Rod, put it in the fisher, watched it catch a fish and then it just disappeared.  Is there a fix underway for this since this is 1.12 and you're making it for 1.12?

**Comment by PrinceOfAmber** [comment]
Added this to RF. thanks for being patient, took me a while @JaRyCu  . latest version tested and working with flux infused rod https://minecraft.curseforge.com/projects/cyclic/files/2501283
