### ISSUE TITLE
Scaffold Fall Damage

### ISSUE THREAD

**Issue by meerple** [PrinceOfAmber/Cyclic#455]
Minecraft version & Mod Version: MC 1.10.2 Cyclic 1.10.29

Single player or Server: Single player

Describe problem (what you were doing / what happened): Going down the side of a Responsive Scaffold makes you go very fast downward and it hurts when you hit the ground.

**Comment by PrinceOfAmber** [comment]
Yeah, it should stop fall damage just like a ladder. i will look into this today or tomorrow

**Comment by PrinceOfAmber** [comment]
Sorry its been a while.  You can climb down it like a ladder but it works differently.  Since it doesnt stick OUT of the block, and instead you are sticking into it; in order to climb on the block you have to be always moving forward into it.  

But moving forward moves you upwards, and holding shift (sneak) and forward moves you down safely with no fall damage.
