### ISSUE TITLE
Some suggestion (enchantment storage solution)

### ISSUE THREAD

**Issue by forestbat** [PrinceOfAmber/Cyclic#462]
Now I‘m tired of enchanted items which is from mob grinder，will you make a inventory which can save plenty of enchanted items？

**Comment by PrinceOfAmber** [comment]
You mean something like a storage drawer or barrel, but it stacks together things with the same enchant?   Makes sense.  I always have boxes and boxes full of random enchanted books and its hard to dig through them all, would be nice to have one big box of 'all sharpness' piled in, and see how many of each level.

Would be harder to with items, since each can be damaged a different level and be different materials.

**Comment by forestbat** [comment]
Okay thanks，I hope this kind of inventory coming out very much。

**Comment by Ash70** [comment]
Perhaps in the shape of a bookcase?

**Comment by PrinceOfAmber** [comment]
Hey I know its been ages and ages, but I came back to this and I have a working prototype.  Just needs some polish and automation.  GIF showing it in this link

https://www.reddit.com/r/feedthebeast/comments/7mpve7/working_on_something_new_ender_library_used_for/

**Comment by Ash70** [comment]
I like it, but as aesthetics go I would go with bookcases. Esp. since one would probably place these near the enchanting area (library). 
I see you mentioned logo's and/or icons on reddit; I have long thought those (for both enchants and potions) would be better implemented using item-frames. But I'm sure whatever you decide will be good :) 

However, the OP asked for storage of items with the same enchant. Perhaps I misunderstood; but I thought it meant being able to store different items (e.g. an unbreaking bow and an unbreaking chestplate) together in the same slot? If I misunderstood: disregard my stupidity.

**Comment by PrinceOfAmber** [comment]
Yeah, the original post was "save plenty of enchanted items", but literally any box in the game can do that. 64k disk in refined storage or something.  If i had an iron sword and a gold sword with matching enchants, I have no idea how I would "barrel" those together.

  I kind of took a left turn and came up with this idea of storing enchants as pure data.   Basically if you have a mob grinder or fish farm, get all your enchants on books, and then automate it into this new system (like storage drawers), it peels the enchants off the books and stores it.  So each block has 4 sections, each section can store 64 of one enchant (same type and level).  Peel off at anytime using a book.

Its not perfect, its not 100% done and it could use improvements, but its a thing.  I am looking into my own improvements, and of course new suggestions can always be opened as usual

So yeah latest release has the new Ender Bookshelf blocks.

https://minecraft.curseforge.com/projects/cyclic/files/2515962
