### ISSUE TITLE
1.11.2 Cyclic + Baubles 

### ISSUE THREAD

**Issue by Rumaruka** [PrinceOfAmber/Cyclic#464]
Minecraft version & Mod Version:
Minecraft 1.11.2
Cyclic 1.5.10

Single player or Server:
Single
Describe problem (what you were doing / what happened):
Azanor change API in Baubles

Crash log (if any):
https://pastebin.com/FLr25HjU

**Comment by PrinceOfAmber** [comment]
Crash log says ": Caught exception from Botania (botania)
Caused by: java.lang.NoSuchFieldError: CAPABILITY_ITEM_BAUBLE"

and "  at vazkii.botania.common.item.equipment.bauble.ItemBaubleCosmetic.<init>(ItemBaubleCosmetic.java:73)
    at vazkii.botania.common.item.ModItems.init(ModItems.java:390)
    at vazkii.botania.common.Botania.preInit(Botania.java:132)"


I will get the latest 1.11.2 baubles to make sure i dont have the same issue though I guess

**Comment by PrinceOfAmber** [comment]
Needs to be posted here as per my previous comment https://github.com/Vazkii/Botania/issues
