### ISSUE TITLE
[1.10.2] Improve usability of the upgraded inventory and crafting

### ISSUE THREAD

**Issue by tommyTT** [PrinceOfAmber/Cyclic#47]
I love the idea of having a larger inventory and also crafting available on my player at all time. So far I always had to use different mod items. In playing around with the Cyclic upgrades I found out, that the current implementation hinders me from being really effective. Here are some points you might consider for future versions:
The buttons are too hard to click, especially if you want or need quick access. They are too small and the crafting button overlaps with the helmet slot. It happened a few times already that all of a sudden my helmet was gone. It was still there and reappeared after clicking the helmet slot again, but it wasn't rendering any more. It would be much easier to have the buttons outside the normal GUI like in the 1.7.10 versions and similar to the way Tinkers adds the pages to it's GUIs since 1.8. It would be also very helpful to have shortcuts to directly open the extended inventory (e.g. Shift + E) or crafting. I wonder if it wouldn't be better to completely alter the normal inventory screen in a similar way like the old Creative+ did it? This might be too much, I don't know!?

**Comment by PrinceOfAmber** [comment]
Keyboard shortcuts would be pretty easy to add, yeah for sure.  

  Yeah the button slot overlap; i should find a better place for it. 

I will look into the other stuff too.


Thanks!

**Comment by PrinceOfAmber** [comment]
I couldnt figure out how to do the super fancy tinkers style inventory.  If i move them outside or above the inventory, i will probably conflict with other mods, as i have seen tons that add tabs up there to the inventory.  The place where i put the buttons was inspired by the mod 'Baubles' since it puts a button in the top right of the portrait.  

But i DID add the keybinding  . it opens the extended inventory if unlocked, otherwise it opens the normal one.  Defaults to R but its easy to rebind to shift-E

and they will not cover up the helmet now.

This and more changes are coming out in 1.3.5.  Im always open to more ideas!
