### ISSUE TITLE
Possible Anvil Dupe

### ISSUE THREAD

**Issue by tigerdan2** [PrinceOfAmber/Cyclic#495]
Minecraft version & Mod Version: 1.10.2 Cyclic-1.10.2-1.10.29

Single player or Server: both 

Describe problem (what you were doing / what happened):
Possible Dupe Glitch
when Extra Utilities is installed, you can dupe anvils using "Flat transfer Node"
to craft them with a normal transfer node and one anvil ,but you dont loose the anvil
when you uncraft 8 of them using your uncraftingtable you get one transfer node, AND one anvil
that means you can craft 8 flat transfer nodes again, and get one extra anvil every time you do this

**Comment by PrinceOfAmber** [comment]
Yeah, the uncrafter is quite dumb by design. it just looks up the first recipe it can find.  I didnt add a "pick which recipe to reverse" since thats easy to exploit.

There is a full whitelist and blacklist system to address issues like this, so you could block anvils from being uncrafted specifically by targeting the item.

So in a way this is kind of a feature, and/or it is fixed by config.

This does give me an idea though, I should probably tweak it to give Preference to vanilla recipes over recipes added by other mods.  The anvil has a perfectly safe vanilla recipe to uncraft, why is it instead adding some other recipe added later.
