### ISSUE TITLE
Flight enchantment on Elytra

### ISSUE THREAD

**Issue by Ash70** [PrinceOfAmber/Cyclic#498]
Just a random idea. But what would you say to a flight enchantment (rare) which can only be placed on an elytra, granting you creative flight when wearing it. It sort of is in keeping with vanilla (requiring an elytra to fly).
Not sure if it fits your mod or if it is possible (it might mean creating an otherwise non-functioning elytra because of the way it works? Not sure)
Feel free to dismiss/close this suggestion.

**Comment by PrinceOfAmber** [comment]
Custom elytra enchants are a good idea. 

But i dont know if it makes sense to do it as creative flight.  I already have a food that does that, and other mods have all sorts of ways to fly.  Maybe a way to increase speed or some other way to improve them.

**Comment by PrinceOfAmber** [comment]
Im not the biggest fan of creative flight myself, but if I do add it in future ill have to find some new different way.

In one of the recent updates [1.10.3] I changed the Multi-Jump enchantment so that it can go on more gear, not just boots.  So you can put it on elytra.  Try it out, it works really well, basically you do not need fireworks. You can jump a few times from the ground, start flying, then while gliding you can do more mid-air jumps to keep your height going.

For this I am not going to add other elytra enchants.
