### ISSUE TITLE
Uncrafter Doesn't Return Nether Stars

### ISSUE THREAD

**Issue by TheDreamweaver** [PrinceOfAmber/Cyclic#507]
Minecraft version & Mod Version:

Minecraft 1.12.1
Cyclic 1.8.2

Single player or Server:

Server

Describe problem (what you were doing / what happened):

Putting any item that was crafted with a nether star into the uncrafter will return all ingredients except for the nether star.

**Comment by PrinceOfAmber** [comment]
Yes, this is intentional but its in the config file.  The uncrafter has several config blacklists to tweak and remove things to avoid exploits.  


In config/cyclicmagic.cfg you will see a 'BlacklistOutput' section, so you can just delete '  minecraft:nether_star' from that and then it should come out again
