### ISSUE TITLE
[Suggestion] Greenhouse Glass

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#523]
This Suggestion is directly taken from AA, so i dunno if you even consider it.
But a block that allows crops to grow faster, when underneath it on daylight only (that's what that glass does) would be very useable by us. Unfortunatley, as i already explained, AA is too freaking Magic and does not allow disabling anything.

**Comment by PrinceOfAmber** [comment]
I do already have the Sprinkler that grows plants faster, added pretty recently.  Have you checked that out?

**Comment by D3nnis3n** [comment]
Ah, no i didn,t. Will it only work in Sunlight?

**Comment by PrinceOfAmber** [comment]
It works whenever there is a block of water below it, should work on pretty much all growable stuff

**Comment by D3nnis3n** [comment]
Will it only Speed up the process when it's day? This is a Special Feature of the AA Greenhouse Blocks. I would consider it speeding it up all day a bit op, but indeed Fitting the style that water is being pumped at all time.

**Comment by PapiDimmi** [comment]
I do agree that Actually Additions is magic. It adds too many OP things. Even smaller things like its storage crates and foods are OP. It’s also barely configurable at all. Actually Additions is my least favourite tech mod, and I wish that every single modpack didn’t have it.

A block similar to Actually Additions’ greenhouse glass would be a great addition to Cyclic!

**Comment by PrinceOfAmber** [comment]
I love AA, especially the cool crafting system with the pedestals.  But its ok to not like things, and I agree it should have as many config options as possible. 

 I feel the same way about EXu2 and some other mods, not configurable enough, hard to disable or change things.

For greenhouse glass, would 'nt it be overpowered since I already have a sprinkler added?  It does the same thing as a sprinkler right, just speeds up growth?

Im keeping it on the list but theres tons of other stuff im planning too.
