### ISSUE TITLE
[Question] Config Variables

### ISSUE THREAD

**Issue by D3nnis3n** [PrinceOfAmber/Cyclic#529]
Hello, i can't seem to find items for the following variables or do not know them or the Feature behind. Would you mind explaining them (maybe also in the config?)
        B:EnderBlaze=true
        B:EnderBombs=true
        B:EnderDungeonFinder=true
        B:EnderLightning=true
        B:EnderSnow=true
        B:EnderTorch=true
        B:EnderWater=true
        B:EnderWool=true
        B:ChestBag=true

I'm also unsure what
        B:"Pass-Through Click"=true
really does mean, as i don't seem to understand the description? The chest opens when i place a sign on it and run into this, or how is that meant?

_Also, this:
        B:"Name Player Skulls with Sign"=true
How does this work? Player skulls are unavailable to get in the normal minecraft? oO_

**Comment by D3nnis3n** [comment]
I now found out how the Player Skulls can be aquired. I'll make an Suggestion for another way of getting them.

**Comment by D3nnis3n** [comment]
I hope you are also not angry that i spammed you with suggestions :D We just noted down what we'd like to have and can't have at the Moment.

**Comment by PrinceOfAmber** [comment]
Yeah a ton of items have had name changes and overhauls throught the time, so now the config name doesnt match the item name.... , and i havent wanted to change the config name since then old config files wouldnt work.

I need to put in descriptions or comments on these outdated ones to state which CURRENT item it hits.

**Comment by D3nnis3n** [comment]
I got most of them out, despite the ones noted above. Would be great if the config could be updated. I can't find a ChestBag at all for example. There are only two bags - and those are other variables.

**Comment by PrinceOfAmber** [comment]
Looked into this.

I can't really change the key, the part where it has B:____ = true , because that would break older config files that rely on it.

What I can do is change the description text freely, so i will addd the block ID or item ID into that.  So it will look like this


  # Set false to delete - requires restart (cyclicmagic:beacon_potion) [default: true]
        B:PotionBeacon=true



That way if you are in the f3 mode to see the item data on the tooltip, you can match it that way.

**Comment by D3nnis3n** [comment]
There seem to be items in that do no longer exist.

Am 14.10.2017 08:05 schrieb "Sam" <notifications@github.com>:

**Comment by PrinceOfAmber** [comment]
In hindsight, maybe i do need to overhaul the config file. it should be fine as long as i bump it up a major version, something like 1.10.0, and not too much will change anyway

Anyway, that has to be a future thing, for your information here at least i can list this out

most of them kind of match the item id

B:EnderBlaze=true  is :ender_blaze
B:EnderBombs=true is :ender_tnt_1 up to 6
B:EnderDungeonFinder=true  is :ender_dungeon
B:EnderLightning=true  is :ender_lightning
B:EnderSnow=true  :ender_snow
B:EnderTorch=true   :ender_torch
B:EnderWater=true is :ender_snow
B:EnderWool=true   :ender_wool
B:ChestBag=true  --- i think this is one of the ones that got removed, "ChestSack" is the  :chest_sack item

**Comment by PrinceOfAmber** [comment]
Moved to my 1.13 only backlog, will get done there but not 1.12  https://github.com/PrinceOfAmber/Cyclic/projects/2
