### ISSUE TITLE
Exp Pylon Bug - OP XP :)

### ISSUE THREAD

**Issue by DigitalSketch** [PrinceOfAmber/Cyclic#545]
Minecraft version & Mod Version:
Minecraft 1.12, Cyclic 1.8.6 (ATM 3 modpack)

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
Bit of an OP bug... I carry around an Exp pylon with me and dump my experience into it, then have it spray out the XP orbs when I need to mend my armor or tools.  When I'm done, I break the pylon to carry it with me.  I've found that if you have a Draconic Item Dislocator, and have it on, the XP will keep getting sucked into me.  There aren't any XP orbs around, and no Exp pylon, it just does it... and so quickly that I can get 1000 levels in just a few seconds.  It doesn't mend anything, just fills the levels.  Has a radius of about 5 blocks where if the Item Dislocator is on, it brings in fake experience.  It never expires either, so you can stand in that area and your levels will increase dramatically.

Crash log (if any):

**Comment by PrinceOfAmber** [comment]
I remember this happening in an older verison,.. I thought some fixes came out for both mods to fix this.  I will check it out again in newest versions.


The old report for reference https://github.com/PrinceOfAmber/Cyclic/issues/475

**Comment by PrinceOfAmber** [comment]
Re-testing with the most latest up to date ATM 3 modpack. its on MC 1.12.2, cyclic 1.9.5, draconic  2.3.4.265, forge 14.23.0.2512

So far it doesnt seem to happen with these new versions.

My testing process is

In creative use an EXP bucket to fill up the pylon full. 

Give myself an Item Dislocator, turn it on (sneaking so its glowing)

then go survival and give myself zero exp

In the pylon, turn Collect Off, Spray On, but only leave spray on for a short time, maybe getting level 30. Pylon is at about 17k

Turn spray off, note that collection stops right away.

In pylon, press ALL button to deposit all.  When pylon is full, player should be at /roughly/ zero exp, no extra levels.

Repeat a few times, and i notice no duplicated EXP orbs.

So as I thought, this was fixed in older versions of draconic & cyclic. But i just wanted to test on my own in the newest versions just to make sure

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this anyway! Better to have a duplicate than no report at all.  ❤️
