### ISSUE TITLE
[Dupe bug] Standard Exchange Scepter

### ISSUE THREAD

**Issue by Unknown151** [PrinceOfAmber/Cyclic#549]
Minecraft version & Mod Version: 
- MC - 1.12.2 and Mod - 1.9.5

Single player or Server:
- Server

Describe problem (what you were doing / what happened):
Wanted to exchange blocks to "Fancify" my base. Realized it wasn't using blocks from my inventory.
I could pick up the "exchanged" blocks and use them. They were not Ghost Blocks.
Tried with Diamond Blocks. I was able to make one block into 5 blocks and convert them to single diamonds.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
were you exchanging the diamond blocks with anything fancy? like chisels & bits or machines or just modded blocks or vanilla ones?

**Comment by PrinceOfAmber** [comment]
I tried to replicate this a bunch of different times and ways.  Cannot replicate so far, made an unlisted video trying to dupe blocks

https://youtu.be/cu4Bh7TFSlU

Question: Can you post the some log files around the time or right after this happened?  Or if you cannot get server logs, does it happen with similar blocks in single player and send those logs?

**Comment by Unknown151** [comment]
I've made a video, replicating the bug on a server: https://youtu.be/3obFdMUsCC4

I'm exchanging simple cobblestone with both diamond and redstone. I'm unable to get serverlogs
The bug does not happen when I'm in singleplayer, only on a server 
I'm playing the "All The Mods 3" modpack.

**Comment by PrinceOfAmber** [comment]
" I'm in singleplayer, only on a server" this is helpful, ill focus on multiplayer , possibly a lag/desync.   

Thanks for double checking all this stuff.

**Comment by Morpheus1101** [comment]
You neglected to mention you also have BetterChunkLoader mod installed with the pack  as well .. are there any other additional mods that you are using not apart of the default ATM3 pack ?

**Comment by Unknown151** [comment]
I have not tampered with the modpack at all. I only installed it and keep updating as needed. 
It must be something the server owner has installed.

Do note, BetterChunkLoader does not involve anything with Redstone Blocks, only Iron and Diamond.
If it was BCL, it would maybe not happen with other blocks than iron and diamond
(I have no modding experience, but that's what I assume)

**Comment by Morpheus1101** [comment]
I tested this out as much as i could on my atm3 server with lothrazar and we were unable to replicate this issue.  Could u check with the server admin and see what other mods has been added that arent apart of the default pack.

**Comment by PrinceOfAmber** [comment]
@Unknown151  we are not saying you messed with the modpack. A server admin can add a server-only plugin, and the modpack for you is exactly the same.  you can't always control what they put on the server.

And also, yeah. BetterChunk loader should not affect redstone blocks.  However when we were testing on a server, i used dirt and grass and cobblestone

Anyway I took some videos on an ATM3 server trying to replicate this
https://youtu.be/7LBVZqafQ-4
https://youtu.be/e2Ect1VhrTI

So there still IS a bug.... somewhere.  Somehow multiple mods or plugins or permissions systems or something are coming together to cause this, i just don't know what or why.

**Comment by EPIICTHUNDERCAT** [comment]
most likely a sponge issue, plugins break things often

**Comment by EPIICTHUNDERCAT** [comment]
Definitely seems like a sponge issue, Loth dont think this is your problem.

**Comment by phit** [comment]
I think what causes the dupe here is that you are assuming the block placement failed just because an exception is thrown anywhere in [here](https://github.com/PrinceOfAmber/Cyclic/blob/29b210fa93e2e6b2502baec127cb675294a803c6/src/main/java/com/lothrazar/cyclicmagic/util/UtilPlaceBlocks.java#L78-L98).

With these changes, there no longer is a dupe.. also added some debug as to why this NPE might happen
https://gist.github.com/phit/55fcf516e32e4028e8d6843469b47400

![](https://i.imgur.com/b1yPSTn.png)

and as you can see it's because you are passing null to `markChunkDirty` which is fine with just forge as it's never used, but Sponge uses it and is [overriding `markChunkDirty`](https://github.com/SpongePowered/SpongeCommon/blob/9411d7d5182f515dcfdf853a79b08c446545ff5c/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L1930)

My proposed solution is don't set `success=false;` in the catch, as the only time it should be false is when `success = world.setBlockState(placePos, placeState, 3);` returns false, not on any random exception.

**Comment by PrinceOfAmber** [comment]
Thanks @curscascis  fix is out in this version https://minecraft.curseforge.com/projects/cyclic/files/2499867
