### ISSUE TITLE
[1.12.2] Cyclic Harvester in a 15x15 area does not gain additional Seed from MysticalAgriculture

### ISSUE THREAD

**Issue by Morpheus1101** [PrinceOfAmber/Cyclic#554]
Cyclic 1.9.5
ATM3 Pack

Server Instance

Having run a cyclic Harvester for over a week on MysticalAgriculture Crops, ive not once gained any additional seeds as i had running other harvesters.

**Comment by PrinceOfAmber** [comment]
So.

I planted a field of coal seeds.

When I harvest with machine, i get Coal essence and fertilized essence.  Never any seeds

When break the plant with my empty hand, i get that plus also coal seeds.

Thats basically what you mean?

**Comment by PrinceOfAmber** [comment]
As i continue testing and breaking them by hand, seems like the plants always only ever drop exactly one seed, and no more.

When i use the 'gentle right click harvest' from pams, i also get no seeds.  So by design they are "re-using" one of the seeds to replant.

With normal crops (vanilla, other mods like rustic or pams) you get a semi random number of seeds.  Wheat for example, you could get up to 3 seeds when fully grown.  Thats why  its not noticed as much, you still get seeds but not as many.

This is by design, it uses the same logic as gentle harvesting and is re-using the seeds to replant.

**Comment by ouroborus** [comment]
AFAIK, MA seeds are configured by default to never drop seeds on gentle harvest and drop exactly one seed on break. Given what the mod does, this isn't surprising. I don't think you're intended to get a billion seeds after just crafting one.

**Comment by PrinceOfAmber** [comment]
Yeah the getting extra seed issue i think will not be resolved, but i did find an issue that may or may not be related to this  and i found a fix.

Might not affect this, since its still going to try and consume the seed, but might fix some edge cases with some crops https://github.com/PrinceOfAmber/Cyclic/issues/569
