### ISSUE TITLE
Air Charm Causes Kick on Server for Flying

### ISSUE THREAD

**Issue by cjm721** [PrinceOfAmber/Cyclic#560]
Minecraft version & Mod Version:
1.12.2, 1.9.6

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Using the Air Charm causes you to be kicked from the server for flying due to the stepping only being set on client.

**Comment by PrinceOfAmber** [comment]
This shouldnt happen if server has the allow flying config set up.

But .." due to the stepping only being set on client.".. sounds like a good change to make regardless, better for desync too . looking into it

**Comment by PrinceOfAmber** [comment]
Found out some learnings.  Setting the players motion properties server side flat out doesnt work, updates are ignored.  Reason is since the vanilla system is built-in from the ground up to take motion from the client player and send to the server . This makes sense since motion in the end comes from player  input (keyboard, mouse, etc).

The vanilla server is just doing what its built to do: it looks at its own flight config, sees a player not on the ground touching blocks, and fires up a red flag.

When I change this 

`allow-flight=true
in the server.properties file`

Then it works, i can Air Charm all day

I'm gonna say this is working as intended.  If server owner wants modded stuff that allows flight, they can control it there. 

**Thanks for reporting this though,** it was worth looking into for sure, and I learned something new as well.

**Comment by cjm721** [comment]
Most modded flight does not require that to be true. Setting it to true tells the server to just trust the client said possistion which allows the client to cheat in many ways.  To fix this need to actually spawn in non air blocks around the player or at least interrupt the kick event (rather the first as the second still has the same major implications).
