### ISSUE TITLE
Duping glitch with inventory

### ISSUE THREAD

**Issue by NightFan92** [PrinceOfAmber/Cyclic#563]
Minecraft version & Mod Version: Cyclic-1.12-1.8.6

Single player or Server: Server

Describe problem (what you were doing / what happened):
> Eat inventory upgrade
> Fill extra inventory (with ex. dirt)
> Shift click item from vanilla inventory to extra inventory
> stackable item doubles every time if it's not in extra inventory

I can redo this again and again, and could get it work with friend

**Comment by PrinceOfAmber** [comment]
This has been fixed in newer versions . see 

https://github.com/PrinceOfAmber/Cyclic/issues/518
and 
https://minecraft.curseforge.com/projects/cyclic/files/2487756

Thanks for reporting anyway! Better to have it reported or not.  But there are some bigger modpacks out there that haven't updated yet though.
