### ISSUE TITLE
New 'Tree Harvester' block similar to current Harvester (Harvester doesn't work on tree logs & replant saplings)

### ISSUE THREAD

**Issue by Gunner76th** [PrinceOfAmber/Cyclic#574]
Minecraft version & Mod Version:
MC 1.12
Cyclic 1.9.8

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Placed the Harvester down expecting it to harvest vanilla trees, as well as trees from Integrated Dynamics. Harvester failed to harvest either set of trees. The screenshots are from when I was trying to use it to harvest the Integrated Dynamics menril trees. The last one is testing it on vanilla spruce trees. I tried it on both single as well as area, and nothing seems to work.  

![image](https://user-images.githubusercontent.com/5566872/32686594-9b61018c-c675-11e7-942c-74472c3a9c29.png)

![image](https://user-images.githubusercontent.com/5566872/32686596-a336c6b2-c675-11e7-9e68-85a87b8d1031.png)

![image](https://user-images.githubusercontent.com/5566872/32686606-00badd32-c676-11e7-8139-264aa9308592.png)

**Comment by PrinceOfAmber** [comment]
Yes, this is by design. The harvester only works on crops and plants and things.

For chopping trees you can use the "Controlled Miner", and you can give it an axe and also whitelist the logs. This will let you harvest logs automatically


This gives me an idea actually: question @Gunner76th , would it be worth me adding a dedicated "Tree Farm" block? Some combination of a harvester and a block miner that harvests/replants trees?  Let me know what you think.

**Comment by Gunner76th** [comment]
Actually yes, that would be a VERY good idea, as it would add in the equivalent to the harvester which iirc already does the harvesting and replanting, does it not?

**Comment by PrinceOfAmber** [comment]
It chops trees from the bottom up and replants saplings.  Does not collect loot, but easy enough to use the cyclic Item Collector for that (or other means of course)

![2017-11-23_20 54 50](https://user-images.githubusercontent.com/621529/33195908-9565d5b2-d090-11e7-952c-b7643ac90b6c.png)
![2017-11-23_20 54 57](https://user-images.githubusercontent.com/621529/33195909-957b3f38-d090-11e7-82ee-348d5c1dd932.png)

**Comment by PrinceOfAmber** [comment]
Fix version Cyclic-1.12.2-1.10.0
