### ISSUE TITLE
New EXP Pylon doesn't bottle + suggestion for it

### ISSUE THREAD

**Issue by zefie** [PrinceOfAmber/Cyclic#582]
Minecraft version & Mod Version:
MC: 1.12.2, Mod: 1.9.11

Single player or Server:
MP Server (not public but can share with devs if needed)

Describe problem (what you were doing / what happened):
Ever since the changes to the EXP Pylon, the only thing I can really do with it is add and remove XP (via the interface or pipes). Bottling does not work. Spray, you said was intentionally removed (though personally I found it useful, such as repairing Mending items)

Crash log (if any):
Not a crash

Notes:
This is both a bug report and a suggestion, which I know is kind of annoying, but the bug is that it doesn't seem to bottle the XP. I should note that everything was fine before I updated from 1.9.8, but I did find the negative XP bug and that is why I wanted to update, since I seen in your changelog that you fixed that.

Suggestion 1:
The suggestion, honestly, would be to revert to the old interface. I noticed in your commit logs and changelog that you removed spray because you wanted more room for buttons. I'd suggest checking out Thermal Expansion's code for the "Energy Cell", they have SHIFT and ALT modifiers on their +/- buttons. ALT offers lower amount for fine tuning, SHIFT offers larger amount for bulk processing.
This could solve both problems (needing more options to import, plus having room for spray).

Otherwise, Suggestion 2:
If this is not desirable or possible, please consider offering the spray option in another way. What I was gonna try, before I realized I can't bottle, was putting the EXP Pylon on top of an "Automated User", and letting the EXP Pylon give the Automated User it's bottled EXP, in which the Automated User could throw it for me. I feel this is a fair alternative to spray, as it would accomplish the same thing, and is slightly less cheatsy, since now it will cost Glass Bottles.

Sorry if this post is all over the place, feel free to let me know if you need any clarification.
Thanks for the great mod!

**Comment by PrinceOfAmber** [comment]
The bottling was working in my tests, i just removed the method of turning it off so ill make sure to test that.

Ill take some time and look into the other stuff

**Comment by PrinceOfAmber** [comment]
@zefie  did you like the "spray" feature? did you use it?  It only exists because it used to be the only way to "withdraw" exp.  I can bring it back if its useful but it seems kind of silly.  also , as noted in other bugs, if spray and collect are both on it creates server tick/lag issues and is pointless.

"letting the EXP Pylon give the Automated User it's bottled EXP, in which the Automated User could throw it for me. I feel this is a fair alternative to spray," This should work already, ill test and make sure this works (with a hopper in between), that would be neat.  

I will look into the energy cell click system, I think i remember not liking it at the time but ill play with it to be sure, maybe its great.

**Comment by PrinceOfAmber** [comment]
I will look into the energy cell click system : I like it, basically regular click does 50, and shift click coes 1000, and the tooltip also shows the amount, and updates along with shift key being held.  

I think this is neat, for example i could just have one withdraw and one deposit button, and it defaults to 50 or 10, but shift does the 500.


I think when i go to convert to this, I should review ALL blocks/screens, and update them all at the same time, so everything stays consistent. I have several with + - buttons (fan, redstone clock, and others).  and then since is a "big-feeling" change, it will probably be in a major version so like "1.10.0".  so ill put this on the backlog

**Comment by PrinceOfAmber** [comment]
for some reason, the Auto user did not accept hopper/pipe input. fixing that in the next release so you can do this 
![2017-11-17_23 17 12](https://user-images.githubusercontent.com/621529/32978001-dcb7139c-cbed-11e7-8d7e-5dad049e5251.png)

**Comment by zefie** [comment]
Yeah, I'm not sure why I can't bottle. I put in the stack of empty glass bottles and it just sits there, even if the pylon is full.

I'm using a custom modpack, I can't really release it because its based on FTB Horizons III so I don't want to step on their toes. But I can link you in private if you would like to try it. Its basically FTB Horizons III with updated mods and a few extras that really shouldn't be breaking yours (such as OpenComputers).

As for spray, yeah it was useful to us to repair items with mending enchanted. I did notice the issue with spray and collect but maybe the button could be multi toggle? Instead of "Collect: on/off" it could be "Collect" "Spray" "None"?

**Comment by PrinceOfAmber** [comment]
"Yeah, I'm not sure why I can't bottle. " sorry, thought i was clear before I found a bug in this,  (basically during upgrade they can get stuck in off mode).  fixed in next release which will be 1.9.13 sometime soon.

 "Collect: on/off" it could be "Collect" "Spray" "None"

.... yep, i should have thought of that before, it would be good combined with redstone toggle.  And I didn't think about mending, of course thats a good use

**Comment by zefie** [comment]
"basically during upgrade they can get stuck in off mode" don't know why I didn't think to try to make a new one instead of fighting with the existing one :D

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2501283
