### ISSUE TITLE
[Suggestion] Just more things : moon phase sensor; arrow target / damage measuring

### ISSUE THREAD

**Issue by GrzechuGrek** [PrinceOfAmber/Cyclic#600]
I has few suggestion:

1. Soulstone should has a FireResistance(1:00) besides other effects. This can be very useful if player suddenly drop into lava.

2. A moon phase sensor. This block looks similar to vanilla light sensor but emits redstone signal depending a moon phase: 
new moon - 0(off)
waxing crescent/waning crescent - 3
first quarter/last quarter  - 7
waxing gibbous/waning gibbous - 11
full moon - 15(max)

3. A cooked egg. A minor food item. Just cook egg in furnace. :)

4. A dummy training doll. Something like MmmMmmMmm mod.

5. Shooting targets. This block emits signal after being hitting by shooting arrow. Strength of signal is depend on how close of centre this block, arrow did hits.

**Comment by PrinceOfAmber** [comment]
All great ideas!  I'll look into all of them.


.... Not sure about adding a very plain old food item like a fried egg unless it does something extra.

**Comment by PapiDimmi** [comment]
>A cooked egg. A minor food item. Just cook egg in furnace. :)

Plenty of mods allow you to cook an egg, even some mods that aren’t entirely food-related, like AbyssalCraft.

There is no point in Cyclic adding a boiled/fried egg, too. Does Cyclic even add food at all, aside from the corrupted chorus? I don’t think so.

Some foods would probably be pretty neat in a mod like Cyclic, though. Maybe there could be a random chance to get an edible bug by breaking dirt, grass, or wood.

**Comment by PrinceOfAmber** [comment]
1. Yes i will add this

2. Yes i will add this, but it won't be anytime soon

3. I just cant think of anything unique that a cooked egg would do, and MC already has lots of boring food. Yeah there are a bunch of foods in cyclic, but they all DO something. The heart container is technically food, but it isnt in the mod /because/ its food.  Same reason I dont add any blocks that are purely decorative blocks, the mod is intended to be just a giant toolbox of fun and/or useful things.  If eggs had no purpose that would make sense, but eggs are used in pumkin pie, so you can kind of eat them already.  

4. The testing dummy just got updated.  So I may or may make my own version but only if i can think of something different enough https://minecraft.curseforge.com/projects/mmmmmmmmmmmm then again that leads into 

5. A projectile target is a great idea.  Thats basically #4 but with a new different twist on it.  And if i get that working, i can go back and look into non-projectile damage too.

**Comment by PapiDimmi** [comment]
I love number 5 too!

**Comment by PapiDimmi** [comment]
I love idea 5, too!

**Comment by FryoKnight** [comment]
Oh! May I reconmand a block for organized villager trading? OpenBlocks used to have one where you place it down with an area of villagers, then you could see a while most of different trades. 
Then you select the trade you wanted, it would open the villagers trade interface, and it was business as normal!

I totally miss that... ;w;

**Comment by GrzechuGrek** [comment]
@PrinceOfAmber 
I'd completely forgot to mention.... one more thing:

6. Alarm block/machine! This block when powered playing loud sounds like siren, bell(traditional and electronic), warning and alerts sound etc.
Like this: http://mod-minecraft.net/alarmcraft-mod/

**Comment by PapiDimmi** [comment]
A doorbell would be cool, too.

**Comment by PrinceOfAmber** [comment]
Hey i know its been ages, but I almost mostly finished  the moon phase sensor and the redstone bullseye arrow target.  

Im in talks with my audio & modelling friend for alarms & doorbells, so that stuff is in planning stage.

The trading block sounds awesome, i do already have trading almanac but maybe.


I have an idea for damage training dummy, but might not pan out.

**Comment by PrinceOfAmber** [comment]
Bullseye target, crash test dummy, and moon phase sensor have been added to the latest release https://minecraft.curseforge.com/projects/cyclic/files/2563194
