### ISSUE TITLE
Crash when placing fluid pipe next to a charset tank

### ISSUE THREAD

**Issue by medsal15** [PrinceOfAmber/Cyclic#605]
**Minecraft version & Mod Version:**
Minecraft 1.12.2; Cyclic 1.10.2 for 1.12.2

**Single player or Server:**
Single player

**Describe problem (what you were doing / what happened):**
I placed a fluid pipe next to a [charset](https://ci.elytradev.com/job/CharsetMC/job/Charset/job/1.12/) tank.

**Crash log (if any):**
https://pastebin.com/YVtMYsF6

**Comment by GrzechuGrek** [comment]
This same/similar crash when I'm trying connect fluid pipe to other fluid pipe on downward or on water.

**Comment by PrinceOfAmber** [comment]
Dug into this.  Its caused by some error inside the charset tank as shown in the first line
`t pl.asie.charset.module.storage.tanks.TileTank.fill(TileTank.java:302)`

Other mods arent doing this. But for my end I can at least catch the error and print to the long instead of letting it bubble up and crash

**Comment by PrinceOfAmber** [comment]
Update: it was also my fault, i was passing NULL fluid stacks around.

**Comment by PrinceOfAmber** [comment]
no more null stacks https://minecraft.curseforge.com/projects/cyclic/files/2508261
