### ISSUE TITLE
[Suggestion] Climbing Gloves enhancement

### ISSUE THREAD

**Issue by Vyraal1** [PrinceOfAmber/Cyclic#622]
**Proposed**
Replicate vanilla minecraft ladder's ability to just only hold shift while on a wall to stay in place. 

**Current**
Right now in order to stay at a constant Y level, a player has to BOTH walk into a wall and hold shift, making it very difficult to look around while stay on the wall.

**Comment by PrinceOfAmber** [comment]
I think i tried to do this when i was first working on it, I can check it out though.

From what I remember, ladders work because you are /inside/ the ladder block, just like being inside water, its a non-solid block.  

But when standing beside stone, how do we know the player wants to climb or just walk by?  This is where i use "motion towards the flat face" to detect

**Comment by PrinceOfAmber** [comment]
I did some testing and i dont think this is possible the way I want it to.  This works fine as is, and there are other vertical motion things such as multi jump, air charm, chorus, etc.
