### ISSUE TITLE
Error opening inventory crafting table.

### ISSUE THREAD

**Issue by cody-code-wy** [PrinceOfAmber/Cyclic#624]
Minecraft version & Mod Version:
Minecraft version 1.12.2
Cyclic version: 1.10.3
In modpack: Enigmatica 2 v1.20 (on twitch launcher)

Single player or Server: Server (both single player, and multiplayer, but the error is server side regardless)

Describe problem (what you were doing / what happened):
May be related to #601 
Upon opening the inventory crafting table, every time, the client is disconnected from the server with error "A fatal error has occurred, this connection is terminated" (same error in single player). The player can reconnect to the server, as the crash does not crash the server or client.

Crash log (if any):
[pastebin.com/DsrVLMft](https://pastebin.com/DsrVLMft)

**Comment by PrinceOfAmber** [comment]
Looks like it has a recipe saved and its trying to craft it but something is failing , some fluid related recipe.  

Probably the same thing as 601, they couldnt get a log file but its the same steps to reproduce

**Comment by PrinceOfAmber** [comment]
Actually looks like a combination of things.  I don't know what mod "appliedfluidics" is, must be something new, but error originated there.  Yes i submitted some incomplete or invalid recipe. but here

  at `com.thiakil.appliedfluidics.util.recipes.BucketProxyRecipe.getInvCopyIfFluids(BucketProxyRecipe.java:87) `

The should just safely return incomplete recipe. I will still add safeguards on my end but thats only half the story, this could happen again, I believe, caused by appliedfluidics if some other mod has crafting (maybe vanilla? not sure?)  .  I could be wrong.

**Comment by PrinceOfAmber** [comment]
This seems fine in latest version. if it happens again after all mods are updated, just reopen issue or make a new one
