### ISSUE TITLE
Uncrafting Grinder & other machines should work on weak redstone power not just strong power

### ISSUE THREAD

**Issue by WenXin20** [PrinceOfAmber/Cyclic#63]
The uncrafting Grinder doesn't seem to work.
Cyclic: 1.4.5
Forge: 2026

**Comment by PrinceOfAmber** [comment]
Hm, I am on forge 2010 but I will update and test it out.

Don't forget It needs redstone power to work, i usually put a lever on the back.

**Comment by WenXin20** [comment]
I put a redstone torch next to it, but that didn't seem to do anything.

**Comment by PrinceOfAmber** [comment]
Youre right, that is weird.

A redstone lamp beside a redstone torch = it is powered.
A dispenser beside a redstone torch = it is powered.

This block beside a redstone torch = not powered. hm

Im not sure why its different than a lamp, i can look into that. something about weak vs strong power maybe

but i am 100% sure that if you **_run a wire directly into the block from a torch that it will work_**.  Also if you put a lever directly on the block it does work.

Since the bug subject is "does not work" and it does work, i will close the issue for now.  **However**, i see how its inconsistent from other redstone based blocks so ill look into making it more lenient in another update

**Comment by WenXin20** [comment]
Ok thanks, I'll try that too.

**Comment by PrinceOfAmber** [comment]
Reopening this

Old versions i was looking for STRONG or direct power, in a coming update i will change all machine blocks to look for WEAK / indirect power to be more consistent with other powered blocks

**Comment by PrinceOfAmber** [comment]
This will be updated in 1.6.0 release
