### ISSUE TITLE
[Suggestion(?] Translation of zh_TW

### ISSUE THREAD

**Issue by sfs131010** [PrinceOfAmber/Cyclic#646]
Hi,
Many Chinese players don't understand or aren't familiar with English, I knew that there is a zh_CN.lang file in the .jar, but it is not convenient enough for some people that play Minecraft with 
Traditional Chinese, so I translated to Traditional Chinese and hope you can add it in the next update.
[zh_TW.txt](https://github.com/PrinceOfAmber/Cyclic/files/1594452/zh_TW.txt)

**Comment by PrinceOfAmber** [comment]
Thanks! I will add this to the next update. 

Also @sfs131010  I have made a few new blocks coming in next update, so append these lines if you have time (green ones are new).  Otherwise I can always update them again in the future.  

https://github.com/PrinceOfAmber/Cyclic/pull/648/files#diff-28ee0f86d5eff9e549bb94eee2cb7805R544

**Comment by sfs131010** [comment]
Thank you very much, I have translated the texts of the new blocks.
[zh_TW.txt](https://github.com/PrinceOfAmber/Cyclic/files/1596919/zh_TW.txt)
18 lines were added inside if I am correct.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2515962
