### ISSUE TITLE
Automated User can't be automatically refueled.

### ISSUE THREAD

**Issue by swestrup** [PrinceOfAmber/Cyclic#674]
Minecraft version & Mod Version: 1.12.2

Single player or Server: Single

Describe problem (what you were doing / what happened): I attempted to pump coal into an automated user to keep it fueled, and was unable to do so. I had assumed that some side would be for refueling, but every side just went into the input slot.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Yeah this changed when I added support for power systems (RF power, etc).  People were reporting bugs that items werent being inserted, but they didnt know that was the fuel side. 

 So now items always work, and you can hook up a power cable to automate instead of coal.

I am glad you reported this though, maybe I need to update documentation to clarify
