### ISSUE TITLE
Problem with Harvester and the mod oershrubs

### ISSUE THREAD

**Issue by tschaha** [PrinceOfAmber/Cyclic#694]
Minecraft version & Mod Version:1.12.2         
Mod 1.12.2-1.10.9

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
When i use the Harvester to harvest ore shrub bushes, it dont take the berries but it duplicates the bushes. The harvestet bush remains and in the inventorie of the harvester is another bush.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
This one? I will take a look https://minecraft.curseforge.com/projects/ore-shrubs

**Comment by tschaha** [comment]
Yes

**Comment by PrinceOfAmber** [comment]
I tried using my standard overrides, but its not easy since the author forgot to publish source code or something.  Anyway, yeah the bushes are set up to not drop berries, theyre just coded that way.

I made an issue to see if anything can be done https://github.com/Lhykos/OreShrubs/issues/21

Related source code on my end https://github.com/PrinceOfAmber/Cyclic/blob/a7b5cedcdfa204b1f043ba06b973dfd298586a8a/src/main/java/com/lothrazar/cyclicmagic/util/UtilHarvester.java#L102

**Comment by PrinceOfAmber** [comment]
In other words, I am stuck unless the other mod author replies and/or updates the mod with compatibility changes.
