### ISSUE TITLE
Machines Fuel Slot 

### ISSUE THREAD

**Issue by JFMillerUSA** [PrinceOfAmber/Cyclic#697]
Minecraft version & Mod Version:
1.12.2 1.10.12

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
Can't import any kind of fuel in any machines fuel slot.

Crash log (if any):
none

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Yeas i had to disable this on purpose and by request.  Since, if this is allowed, then it blocks and causes trouble for import/export of the actual items of whatever youre doing.

For example take the Uncrafter: You want to import raw materials and pull out the results.  But what if you are trying to Uncraft something like Wooden Planks that can also be burned, does it go in fuel slot?

Anyway, all machines run on standard power now, so RF, forge energy, testla , whatever is around will work.  Inside Cyclic you have the Peat Generator in new versions, but of course many other mods have generators.  (fuel slots kind of a leftover from when i was not compatible with energy. i just didnt remove them yet.)  

Sorry; hope this helps!
