### ISSUE TITLE
Modded ore types in Nether and End

### ISSUE THREAD

**Issue by Landstryder** [PrinceOfAmber/Cyclic#709]
Would it be possible to add some modded ores to the ore types that spawn in the nether and the end. Like maybe detect if there is copper, tin, uranium, other gem types, etc... and then add Nether and End versions much like your mod does for the vanilla ores? I greatly prefer your method of adding ore over the NetherOres mod or the other options out there mainly because they overlay on the texture pack I use instead of forcing them to the 16x vanilla texture which stand out horribly when using 32x+ texture packs (I use soartex 64x).

Another awesome thing would be to have some cross mod compatibility with NetherEx to add your ores to the different netherrack variants that are added by that mod and other mods as well if at all possible.

**Comment by PrinceOfAmber** [comment]
Sure, i can start looking into that.  

So maybe
- copper
- tin
- aluminium
- silver
-whatever else is added by Thermal expansion or Immersive Eng ..or maybe mekanism

-- What other mods / ores should i not forget about?

**Comment by Landstryder** [comment]
Nuclearcraft is one of the big ones in my pack, but you got the primary ones covered in your list. Other odd ones that might be good are the ones from Tech Reborn (although it has its own nether based ores) and Advanced Rocketry. Oh and definitely certus quartz and the charged variant

Here is a list of oredict names of some the ores I would love to have spawn in the nether and end in my current pack for reference. It has Nuclearcraft, Industrialcraft, Tech Reborn, Mekanism, Applied Energistics, and Advanced Rocketry as the primary tech mods.

-         oreCertusQuartz
-         oreChargedCertusQuartz
-         oreLead
-         oreUranium
-         oreThorium
-         oreBoron
-         oreLithium
-         oreMagnesium
-         oreGalena (this is like a lead/silver mix)
-         oreIridium
-         oreRuby
-         oreSapphire
-         oreBauxite (this would be the aluminum)
-         oreTitanium
-         oreOsmium

**Comment by PrinceOfAmber** [comment]
Started with the textures first.  Rutile is titanium, so I think this is everything..... Possibly an issue with Boron, dilithium and lithium since the ones i found in the mod are 32x.  might be fine though IDK yet.   

![ores](https://user-images.githubusercontent.com/621529/36938066-fcfbe098-1ed0-11e8-8088-14943e042c39.PNG)

**Comment by PrinceOfAmber** [comment]
Other ore dict entries in addition to above, as a note to self so i remember and keep spelling correct. (ill edit this as I go as needed)

oreTin
oreNickel
oreQuartz
oreQuartzBlack
oreAluminum (register bauxite with both ore dicts, since some mods use this
oreSilver
oreAquamarine
oreCobalt 
oreDilithium
oreSaltpeter (nitre ore)
orePlatinum
oreRutile (the block has both this and oreTitanium, so reg it with both
oreTungsten
oreYellorium
oreMithril (mana infused ore from thermal foundation)

**Comment by PrinceOfAmber** [comment]
Still needs lots of testing for worldgen, compatibility, etc, but here is a 

Progress update:  

![2018-03-04_14 31 32](https://user-images.githubusercontent.com/621529/36951451-e094d296-1fb8-11e8-9040-0f42c9601218.png)

**Comment by PrinceOfAmber** [comment]
using Soartex texture pack 
![2018-03-04_14 35 11](https://user-images.githubusercontent.com/621529/36951493-4950c40c-1fb9-11e8-876b-72ecbac39e16.png)

**Comment by Landstryder** [comment]
Freking AWESOME thanks very very much good sir!

**Comment by PrinceOfAmber** [comment]
Alpha version with this feature is out 
https://minecraft.curseforge.com/projects/cyclic/files/2538731

is disabled by default . if theres any questions feel free to ping me on twitter https://twitter.com/lothrazar , or open an issue if theres a problem or I missed an ore or whatever.
