### ISSUE TITLE
Redstone Carrot has no effect on horse

### ISSUE THREAD

**Issue by xerberus333** [PrinceOfAmber/Cyclic#723]
Minecraft version & Mod Version:
MC 1.12.2
Cyclic 1.14.1
The One Probe 1.12-1.4.19 (used to confirm horse stats)
MultiMC 0.6.1

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
1. In MultiMC, enable Cyclic and The One Probe
2. Create test world in creative mode
3. Spawn Horse using creative spawn egg
4. Feed with Redstone Carrot
5. Horse speed remains the same as per The One Probe UI

Crash log (if any):
n/a

**Comment by PrinceOfAmber** [comment]
The speed goes up in fairly small increments.  For example it might go from 27.0 to 27.9 in one carrot.  

They are very cheap though, so you can just feed half a stack to your horse.

Horse speed should be in F3, i made an example.

![red carrot](https://user-images.githubusercontent.com/621529/37446415-13491d4a-27da-11e8-8d89-f2dd1e0e1526.gif)


 Havent tested with F3 yet, still might be desync issue, or maybe they measure it differently

**Comment by xerberus333** [comment]
I tested using your method above, and you're correct. F3 shows horse speed increasing. This seems to be a visual bug with The One Probe.

**Comment by PrinceOfAmber** [comment]
I looked into this a bit, so we just display them in different formats, no idea whos right or wrong.

On my end, when I say Horse Speed: 33.47, that translates to TOP version of 0.3347

And when my F3 says 37.47, then TOP would read that speed as 0.3747

So just decimal is shifted over.  Also it sounds like your saying that TOP either truncates or rounds off the number, so in both above cases it would look like "0.3". Mabe as a feature request you could ask them to display more precision, so the full "0.3747 shows up"? 

Closing this since carrot is working, sounds like its all cleared up :) 👍
