### ISSUE TITLE
[Harvester Suggestion]

### ISSUE THREAD

**Issue by Morpheus1101** [PrinceOfAmber/Cyclic#735]
Currently once the harvester is full, it will simply spit items out of the top of the machine, after a period of time and occurring with even just a few chunk loaded machines, it essentially kills the TPS of the server.

Also with a few harvesters in the same area, it kills the client FPS quite heavily.

**Comment by PrinceOfAmber** [comment]
What version are you on? This changed fairly recently.

Also, can you define how "full" it is?

  Showing in this gif, when the harvester is completely 100% full, as in all seed stacks at 64, the timer bar stops moving, everything stops.  

Then if i remove even one seed, (all slots have something, but one slot not full) then it knows it has some space left.  

So, yes, if there is some room left, then it will harvest.  And yes, as you can see in that i get a wheat pop in my inventory.  There is no way to tell in advance that the harvest will or will not fit in the inventory (for example, if a crop only dropped berries and nothing else, and it was all full except for 50 berries, it probably has room. but with wheat and seeds its different).  So in a way, the machine is not technically full, but there is nowhere for the wheat to go.  

Same situation would happen if you were gathering carrots, and the last slot had 63, and one harvest grabbed 2 carrots, well one would go in, and the lats goes on the ground.

It shouldnt spawn into the world "forever" , just until its full.  And if you are doing such a large harvest (multiple crop types, Area mode, tons of growth advancers) at that point the tech should be available for pipes to make sure the harvester is just always empty.

![harvestquestion](https://user-images.githubusercontent.com/621529/37563352-22aa4520-2a3c-11e8-922b-3a12a4fbb6c4.gif)

**Comment by PrinceOfAmber** [comment]
If your setup cannot be changed, or the item cables arent enough , Cyclic does have the Item Collector to suck in drops on the ground, which you could delete by sending to the Trash Void

**Comment by Morpheus1101** [comment]
I know this was changed recently as i requested it about this very issue occuring.

I resolved it by hooking it directly into my ME system as this was the only way in which i could pull out what was being harvested fast enough to avoid it filling up.

in this instance there is 4 different types of essence being harvested form the 1 15x15 area etc .. the gif below shows the circumstance in which this occurs

https://puu.sh/zK7nV/4d30a42c3e.gif

**Comment by Morpheus1101** [comment]
What im proposing if possible, is to have a method that somehow prevents this form occuring, such as if it harvests an item and it cant add the harvested item into the internal inventory, it simply stops harvesting untill a internal inventory slot is free.

**Comment by Morpheus1101** [comment]
Any further updates on this at all?

**Comment by Ruchian** [comment]
In the MMD server, I had a farm of 9x9 setup, with the center piece replaced with a sprinkler, so 80 crops to harvest on Area Mode.

It was a full farm of the same Mystical Agriculture crop. I had it connected to two drawers (2048 of the same item storage) and a bunch of machines. Mystical Agriculture, farmed with the Harvester gives you two loot items, one is the standard 'essence', the other is the rare drop 'fertilizer' (the pink stuff in the gif morph showed).
These two items were pulled into the harvester's inventory and extracted from it using pipes towards which leaded towards the other inventories with room. At some point everything was completely filled up. There wasn't any room left anywhere, not on any of the stacks, not on slots. It turned out I forgot one pipe (to void things) which is why this happened relatively quickly. 

What I found the oddest part though is that the farm was running. Like yours I had it set on detect redstone. Due to a foolish mistake on my part, the redstone signal didn't turn off on time. Anyway, at some point too many items were on the floor. FPS was near 2. I could fill my entire inventory about 7 times, while trying to get rid of the way too many items.

All I can say is that something made the harvester unable to stop harvesting, despite it being implanted to detect a full inventory. (In game, I never noticed this by the way. No matter what crop I did, for some reason it just kept throwing everything out at some point.)
Is it possible it is a bug related to area mode or is it something about the mystical agriculture crops? (I suppose it would need testing, but I lack a bit of time and interests enough to do this...)

PS: Although I said rare, the first item I got more than 500.000 items of was that fertilizer. (this due to having more than one farm with a different crop, that happens to drop the fertilizer as well.)

About the suggestion. Maybe you can make it so that the harvester stops when it sees that two or three free (lets just call it buffer) slots are left (for filling) while it is on Area Mode.
And while it is on Single Mode, you can let it fill up the last slots like you'd normally wish to do.
(in other words, effectively you'd have less slots left on Area mode, due to some being there for buffering. If something happens to be in one of those while it is on area mode, the harvester world stop).
I think it is most efficient if you write it in a way to detect the amount of total slots and the amount of taken slots for this. (That way it wouldn't matter where the free slots are.)

**Comment by PrinceOfAmber** [comment]
See changelog of 1.17.3 , partial fix for this ... but it still could happen if output is full for a crop that gives 2+ different items. but only if one is slowly coming out like wheat.  
So gameplay solutions could be:
- set harvester to redstone controlled, so if some nearby chest is full with comparator then harvester is off - then it will just stop until its emptied out or has room
- use single and not area mode
- faster pipes
- trash cans  and/or vacuum collectors

Theres a feature planned for the future sometime  that might help resolve this also :::::  



the problem now is harvester speed is locked, so if it gets too fast for pipes, or they otherwise fill up, you need to havea vacum + void trash ready.  if we could control the harvester speed up and down (item upgrades or something similar ) taht would help.  its been requested and ive looked into it but thats a long term thing.

**Comment by Morpheus1101** [comment]
Wondering if there has been any further devalopment on this issue either in 1.12x or in the 1.14x branch ?
