### ISSUE TITLE
Tinkers Construct Mod Crash

### ISSUE THREAD

**Issue by WenXin20** [PrinceOfAmber/Cyclic#74]
Cyclic v1.5.3
Forge v2073
Crash when opening a tinker construct table, something to do with the terraria buttons.
Here is a [log](http://pastebin.com/e8fWHx9Q), no crash report generated though.

**Comment by PrinceOfAmber** [comment]
I have two workarounds for you to fix this, both in the config file

This is the line here, yep.

 com.lothrazar.cyclicmagic.gui.button.ButtonTerrariaLootAll cannot be cast to slimeknights.tconstruct.tools.client.GuiButtonItem

Whats happening is that Tinkers assumes that EVERY single button on the whole screen is a TCONSTRUCT button, which is not true.  I have a feature that injects my buttons into their screen.

The feature can be easily disabled in the config: named  "TerrariaInventoryButtons" in the inventory category.

Or if you want to keep that turned on, I have a blacklist for this very feature: in the config text file look for 

"Blacklist Container CSV"=

and add onto the end  ,slimeknights.tconstruct.tools.client.module.GuiButtonsToolStation

This means that my buttons will ignore that one specific container that has a problem.  You can see i already have it ignoring 'GuiMerchant' which is the villagers, as well as beacons and brewing stands.

_Technically_, this is a bug in Tconstruct, but only becuase they just assume nobody else will add buttons to THEIR screens, which is normally safe.  (They could do a check IF this button is one of mine, treat it as such, otherwise skip it)

**Comment by PrinceOfAmber** [comment]
I marked as 'wontfix' because there is literally nothing to fix on my end.  Hopefully the two workarounds that are already in the config system work for you :)

**Comment by WenXin20** [comment]
ok, thanks
