### ISSUE TITLE
Various suggestions

### ISSUE THREAD

**Issue by Ithronyar** [PrinceOfAmber/Cyclic#746]
After fairly thoroughly exploring Cyclic's features, I have some observations about how its user experience can be improved.
I actually have several more ideas, but I'm omitting them because they're more invasive, and their benefits are mostly immersion and logic.
Anyway, on to the list.

**1.** Peat fuel creation can be streamlined without any detriment to depth or difficulty. Right now the process is: Peat -> Peat Deposit -> Soaked Peat -> Peat Fuel. Soaked Peat is an unnecessary step whose only purpose is to be make into peat bricks. The peat deposit block should just break as itself and cook down into the brick.
**2.** Minor rename: Peat Bog isn't an ideal name. Either each block is considered an entire region (a bog), or it's a mushy bog block. I suggest renaming it to Bog Peat, or to make the player sink into it and move slower.
**3.** Subjective: The hydrator doesn't look like a crafting machine. When I first tried to use it, I thought it would just hydrate the blocks around it in the world, since it never occurred to me that a block that looked like that would have a crafting window. I suggest a more interesting and unique model that reflects its purpose; maybe a machine that looks vaguely similar to a cauldron, so it's obvious that you have to put things into it. Just some ideas.
**4.** Peat generator needs a new block model and textures. Right now it looks like the automatic fishing net.
**5.** Ender bookshelves and library have badly mapped textures. Some of the books are sideways and their tops and bottom faces should be wood, not more books.
**6.** The 8-bit sound effects are shrill, jarring, and don't fit with the game very well. I suggest an overhaul to the sounds, so they logically reflect the events that they're attempting to portray.
**7.** Charms look washed out due to the enchantment glow, even though their function is strongly indicated by their color. I suggest removing the glow and giving them unique animated textures. This allows them to be more vibrant and reflect their purpose more clearly, instead of the weird purple-white glow that they have now.
**8.** The emerald carrot's effect (turns horses into zombie horses) doesn't make sense. It should be an Infected/Rotten/Undead Carrot (or something like that), made with diseased/toxic/dead things like rotten flesh, spider eyes, etc. It's also kind of expensive, since it just turns horses into an undead novelty version.

About new models/textures/sounds: I can help with them, or even make them all myself if no one else wants to.

**Comment by PrinceOfAmber** [comment]
Yeah you can tell i am pretty bad at textures and models, since many things are just copied from another block (such as the hydrator being the same model as experience pylon).  Ill look at all of these.  

Peat generator needs a new block model and textures. Right now it looks like the automatic fishing net." this was a bug fixed in a release a few days ago.  So check that out, but even so im not in love with how it looks

I would accept pull request for 
- Peat system block models / textures 
- emerald carrot texture (would get a new recipe and name too)
- Hydrator block model / texture 
- ender bookshelf top and bottom texture: I could re-use something like purpur or oak wood, but I'm open to ideas  
- I don't know the first thing about making sound effects, so I just use https://www.bfxr.net/ and hit randomize and tweak settings until something sounds cool.  There are a few effects I really like, but most are them are just in the 'good enough' category, since id rather spend time on new features or bugs. So yeah not opposed to an overhaul.  
- Charms: literally just re-uses the enchanted item glow effect.  This indicates on and off state saved in NBT data.  So yeah if there were a way to instead change the texture, that would be better.  Not sure how but its probably possible.

**Comment by PrinceOfAmber** [comment]
![2018-03-18_22 06 24](https://user-images.githubusercontent.com/621529/37578902-b8b35c2a-2af8-11e8-9b2c-6913ca05e775.png)

**Comment by Ithronyar** [comment]
I had a feeling the peat generator thing was a bug, but I threw it in just in case it was a placeholder. It looks pretty decent now, so I'll hold off on doing anything to it until the more pressing matters are concerned.

If you want to discuss all the details/ideas, Discord is the better choice for that, since I don't really use Twitter.

**Comment by Ithronyar** [comment]
Trying out some animated plates and conveyors without deviating from the original style. They don't seem to be toggleable (they should be; new suggestion?). If their effects can be turned off, they would have to switch to a static texture to show that their effects aren't working anymore.
![plates](https://user-images.githubusercontent.com/26017430/37646637-63657538-2be7-11e8-9a94-7dde1ff86acd.gif)

**Comment by PrinceOfAmber** [comment]
Hey those look amazing!  Especially how the animation speed indicates the speed of the actual movement.

Yeah a redstone signal would be a good addition, like defaulting on but redstone disables.

Also, im not totally married to the specific bright colours; do you think its better in a more natural theme (metals, browns, leather shades?)  Its fine like this too.

We mentioned discord, i am Lothrazar#7738  , im in most of the minecraft related discords too

**Comment by PrinceOfAmber** [comment]
Closing only because we are continuing using discord & pull requests. 

Looking forward to working with you :D
