### ISSUE TITLE
Energy cable/ Energy extraction cable

### ISSUE THREAD

**Issue by Bullorg74** [PrinceOfAmber/Cyclic#788]
Minecraft version & Mod Version:
MC: 1.12,2 
Cyclic: 1.12.2-1.14.9
Forge: 14.23.3.2668

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
Immersive engineering charging station and capacitor. (what I found so far) is not accepting energy from the energy cable but will accept energy from the energy extraction cable. But things like the immersive coresampler will accept from both. Same with chisels auto chisel and some other things I tested.

I find it wierd.

BTW Love the mod :)

![2018-04-26_08 02 54](https://user-images.githubusercontent.com/38103415/39288972-75197a44-492a-11e8-8ef2-6782ec135b34.png)

![2018-04-26_08 03 02](https://user-images.githubusercontent.com/38103415/39288970-72d8fa5c-492a-11e8-8a0b-ecdb3588c216.png)

Also tested in survival

![2018-04-26_08 18 21](https://user-images.githubusercontent.com/38103415/39289037-be1707a2-492a-11e8-85ab-8409bb18e349.png)

**Comment by Bullorg74** [comment]
Hmmm this is wierd.
I made a test "pack" and I still have the same issue with the charging station. And the power cable not delivering power but the extraction cable will. (and the auto chisel is from Chisel)
![cyclictest](https://user-images.githubusercontent.com/38103415/39955939-d9489766-55d7-11e8-8ee5-9ebacafc9020.JPG)
![2018-05-12_11 31 15](https://user-images.githubusercontent.com/38103415/39955957-05ca2e76-55d8-11e8-93f7-36e38617c54a.png)
![2018-05-12_11 31 17](https://user-images.githubusercontent.com/38103415/39955960-081a15c4-55d8-11e8-811d-f21935032765.png)
![2018-05-12_11 31 20](https://user-images.githubusercontent.com/38103415/39955961-0a19ebb0-55d8-11e8-8d16-325f211e29bf.png)

**Comment by Bullorg74** [comment]
And broke and replaced everything after I added Intergrated dynamics. And still same result.
And offcourse also tested if they actually charg and its a Hwyla issue and no wont charge in the empty one but charges things in the full one.
![2018-05-12_11 49 18](https://user-images.githubusercontent.com/38103415/39956114-ad21af80-55da-11e8-93c6-41679e608f0e.png)

**Comment by AstroxV** [comment]
I can confirm this issue in the SevTech modpack. Trying to connect garden cloche with the cables wont work, but connecting it directly to the extraction cable will supply the garden cloche with power. Tested it with a IE capacitor and integrated dynamics battery.
MC: 1.12,2
Cyclic: 1.12.2-1.14.9
Forge: 14.23.3.2676

**Comment by Jandakast** [comment]
Confirmed this is still an issue. In the below image Cyclic Energy Extraction cables will transfer power to the batteries but when attached to the Energy Cable they will not power the chargers or batteries. 

Cyclic: 1.15.5
Immersive Engineering: 0.12-82
Forge: 2702

![image](https://user-images.githubusercontent.com/19498789/40459165-e61ad6e4-5ecd-11e8-975a-570d828daaec.png)

**Comment by SlyCedix** [comment]
Also experiencing this with Immersive Engineering Cloches and all Galacticraft Machines

**Comment by PrinceOfAmber** [comment]
Thanks for the updates looking into it

**Comment by SlyCedix** [comment]
I think I've pinpointed the issue here, the cables are inputting energy from the opposite side that they are connected.

This works: https://i.imgur.com/la2bsL0.png

This works: https://i.imgur.com/pCApeym.png

But this does not: https://i.imgur.com/aOnskBN.png

So something with a sided input will only take energy if the input cable is on the side opposite the one it should be.

I don't have the time to fully run through the code, but it would appear you are doing a `.getOpposite()` on a face that does not need it, I'd assume this is an issue for every cable type.

**Comment by PrinceOfAmber** [comment]
IE charging station: yep: the far left here gets power and the right two do not.

I think youre right about the getOpposite, because for the Cloche, the horizontally oppoisate side also takes power, so the bug hides itself.  Only shows up if Side takes power and side.opposite does not

![2018-06-08_20 28 40](https://user-images.githubusercontent.com/621529/41187265-8dde1eca-6b5a-11e8-9dba-5a7118668bb9.png)
