### ISSUE TITLE
ItemProjectileDungeon interacts with world from a different thread

### ISSUE THREAD

**Issue by Aaron1011** [PrinceOfAmber/Cyclic#863]
In ItemProjectileDungeon#onItemThrow, [the world and an EntityDungeonEye are modified off the main thread](https://github.com/PrinceOfAmber/Cyclic/blob/29c0bcfbc7b39a202f974e84f2e99d1ee1228595/src/main/java/com/lothrazar/cyclicmagic/item/findspawner/ItemProjectileDungeon.java#L85-L103).

While this might appear to work correctly, it can cause an extraordinary number of issues. Even if the chunks accessed by `UtilWorld.findClosestBlock` are loaded, the returned data could be nonsense if the position is currently being modified by the main thread. If the chunk isn't loaded, the problem becomes even worse, since the main thread could also attempt to load the same chunk simultaneously.

To ensure that Cyclic interacts with the world safely, all access to Minecraft objects - even ostensibly read-only access - should be done on the main thread.

**Comment by PrinceOfAmber** [comment]
This all used to be on the main thread, i moved it off specifically by request. The issue was that it used to cause about 1-2 seconds of lag when searching for the target.

Ill try to find the issue where it was reported..

Absolutely I need to check if the chunk is loaded, this seems like a very good thing to implement.

If I assume that the target is "currently being modified by the main thread. ", isnt it still safe though? Since I am only getting a get/read.  So, worst case it might just find a spawner that is "actually gone" in the main thread.

Now that I think about it, could be related to this bug i cannot replicate

https://github.com/PrinceOfAmber/Cyclic/issues/856


Ok so
1. check if chunk is loaded first
2. add a config file entry to disable the multithreading.  Many people like this as it saves the player lag (ex in single player or in Sevtech) but if it causes problems on some servers I can also see the case for it to be disabled

**Comment by Aaron1011** [comment]
@PrinceOfAmber:

> If I assume that the target is "currently being modified by the main thread. ", isnt it still safe though? Since I am only getting a get/read. So, worst case it might just find a spawner that is "actually gone" in the main thread.

Other than adding scheduled tasks, nothing in Minecraft is thread-safe. Absolutely no synchronization is used when reading or writing blocks, so even reading a block from a different thread isn't safe. You have no idea if the second thread will see any kind of consistent view of the world (e.g. it might  see a chunk as loaded, but not properly initialized).

I would strongly advise you to remove this multi-threading entirely. If lag is an issue, you could try two different things:

* Cache spawner locations (e.g. per chunk), and update the cache on a block change event.

* Break up the search into several pieces, each running on a separate scheduled task.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2578660

**Comment by jamierocks** [comment]
Just to pitch in here, I don't actually see this as a fix to the problem. Sadly the way Minecraft currently works means that your default way of doing things breaks the state of the game. Be it a server mod, or just any other mod trying to access that data - there can be synchronisation issues.

I would remove the config toggle, and instead opt to cache data (like Aaron suggested). Yes, lengthy processes are a PITA - but breaking mod compatibility is an even greater PITA for both mods - handling bug reports, as you likely well know, is a lengthy dev-preventing process.

I guess if nothing else, perhaps make the config toggle disabled by default.
