### ISSUE TITLE
[1.10.2] [Bug] Compatibility Issue (Visual) with Tinkers' Construct

### ISSUE THREAD

**Issue by SnowShock35** [PrinceOfAmber/Cyclic#89]
Hello,

I have an issue to report to you regarding your mod Cyclic(Magic). Here are the details of the issue...

### Important Information

* Minecraft 1.10.2
* Minecraft Forge 12.18.1.2077
* Cyclic 1.10.2-1.7.4 (Latest CurseForge Release)
* Mantle 1.10.2-1.0.0
* Tinkers' Construct 1.10-2.3.3a

### Issue Description

When Cyclic is in a pack with Tinkers' Construct, The tool forge and tool station experience weird visual problems causing the input slot of the inventory to be offset and in the incorrect place. However, once one of the tabs is clicked this issue is fixed until the GUI is closed and reopened again.

### Media (Screenshots)

* Without Cyclic
  * Tool Forge: http://ss.snowshock35.com/2016/09/1473605297-d54285ee.png
  * Tool Station: http://ss.snowshock35.com/2016/09/1473605360-d31f0e82.png
* With Cyclic
  * Tool Forge: http://ss.snowshock35.com/2016/09/1473605673-76c8c532.png
  * Tool Station: http://ss.snowshock35.com/2016/09/1473605680-cbee934a.png

**Comment by PrinceOfAmber** [comment]
Thanks for reporting this! Ill have to figure out whats causing this.

**Comment by PrinceOfAmber** [comment]
Can you try to disable something in the config file for me? Click on Mod options, cyclic, then there is an Inventory button, and then a config option named


TerrariaInventoryButtons

Set that to false.  What that option does is add extra buttons to any GUI that are helpers, kind of like the quark buttons. For me that fixes the problem

**Comment by SnowShock35** [comment]
I will test this first thing tomorrow when I'm back from college. Sorry I can't test sooner.  I'll let you know asap of the results and hopefully it's fixable :-)

**Comment by SnowShock35** [comment]
@PrinceOfAmber Okay so I've just tested and yes, the issue is fixed when disabling this option. For now I will disable it as a temporary fix however, if you're able to find a fix for the issue that'd be more than appreciated 😃

**Comment by PrinceOfAmber** [comment]
Yep for sure i looked into it a bit.  Im glad turning off this feature solved the problem, those four buttons are just one minor part of the mod.

I add these to all GUI containers, (but really they are intended for use in things like chests/dispensers to quickly dump and remove items).  And because TCON has so many buttons already, it just messes up their layout.  Which of course it does, they cant expect other mods to inject buttons like that.

I also have a different config entry right at the bottom of the file that I use to blacklist problematic containers ( already exists in current build ).  Anyone can do this if they know the id and path, but its not something obvious like an item id.

So in the next build ill find out how to identify these containers and blacklist them, and then you can still leave this feature on.  Im working some overtime this week at real-life work so hopefully by the weekend.

`  ##########################################################################################################
    # terrariabuttons
    #--------------------------------------------------------------------------------------------------------#
    # Here you can blacklist any container, vanilla or modded. Mostly for creating modpacks, if some containers shouldnt have these buttons showing up.  (TODO: add tinkers construct to the list below)
    ##########################################################################################################

    terrariabuttons {
        # FOR MODPACK DEVS: These containers are blocked from getting the buttons.  By default, anything that extends 'GuiContainer' will get the buttons.   [default: net.minecraft.client.gui.GuiMerchant,net.minecraft.client.gui.inventory.GuiBrewingStand,net.minecraft.client.gui.inventory.GuiBeacon,net.minecraft.client.gui.inventory.GuiCrafting,net.minecraft.client.gui.inventory.GuiFurnace,net.minecraft.client.gui.inventory.GuiScreenHorseInventory,net.minecraft.client.gui.inventory.GuiContainerCreative]
        S:"Blacklist Container CSV"=net.minecraft.client.gui.GuiMerchant,net.minecraft.client.gui.inventory.GuiBrewingStand,net.minecraft.client.gui.inventory.GuiBeacon,net.minecraft.client.gui.inventory.GuiCrafting,net.minecraft.client.gui.inventory.GuiFurnace,net.minecraft.client.gui.inventory.GuiScreenHorseInventory,net.minecraft.client.gui.inventory.GuiContainerCreative
    }`

**Comment by SnowShock35** [comment]
Thank you very much @PrinceOfAmber I appreciate the help 👍

**Comment by PrinceOfAmber** [comment]
Resolved in 1.7.5 by adding default values to the config file (may have to delete the file or that section)
