### ISSUE TITLE
[Curseforge comment] Dungeon finder too fast to see

### ISSUE THREAD

**Issue by PrinceOfAmber** [PrinceOfAmber/Cyclic#90]
MoonFather Posted 3 days ago

can you please make the dungeon finder orb wait a second before flying, and then fly slower? i can't even see where the damn thing goes. i activate it, the game lags for a split-second and the orb is gone.

**Comment by PrinceOfAmber** [comment]
Resolved in 1.7.5

As stated in the changelog, it should fly slower and more horizontal at first.  And of course the particles should be visible to help out as well.

**Comment by xenoflot** [comment]
@PrinceOfAmber Has this quirk resurfaced? I'm using 1.10.2-1.9.2, testing in SSP and if I'm standing at surface level, all I see is a quick flash and I have no idea where it went. The entire lifespan of the orb is about the same as the sound effect so it's about 4 frames and gone!

If I fly up and get 10 or so blocks above the surface, I can see it's going horizontally, but I still feel it's moving 10 times too fast. If I was playing with a bit of lag, even when flying I wouldn't be able to see it.

The "raycast" flight path is problematic because if you're standing on the surface, even if you had a good X or Z separation, because it's flying downwards, it's underground within a millisecond or two :)

I suggest rather than having it beeline for the dungeon, have it behave like the Eye of Ender, heading out quite slowly then hovering at the X & Z at SurfaceY+20.
