### ISSUE TITLE
ConcurrentModificationException thrown when using Block Randomizer; conflict with Signals?

### ISSUE THREAD

**Issue by dsmall3303** [PrinceOfAmber/Cyclic#906]
Minecraft version & Mod Version:
mc 1.12.2
cyclic 1.16.9
Single player or Server:
Singleplayer

Describe problem (what you were doing / what happened):
Was using the Block Randomizer on a floor of mixed Chisel Factory blocks underneath some machinery. This issue seems to be intermittent but repeatable given enough time.

See also https://github.com/MineMaarten/Signals/issues/81

Crash log (if any):
VanillaFix was used to capture the log:
https://paste.dimdev.org/ateyadunoh.mccrash

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by MineMaarten** [comment]
Hello @PrinceOfAmber ,

The cause of this is modifying world state from the network thread (MC is not thread-safe :/), instead of the server/client thread, in the packet handler:
https://github.com/PrinceOfAmber/Cyclic/blob/4b9dd394b672e81e8eed4e1b6e24e77c85dcd105/src/main/java/com/lothrazar/cyclicmagic/item/random/PacketRandomize.java#L84-L116

It would also explain https://github.com/PrinceOfAmber/Cyclic/blob/4b9dd394b672e81e8eed4e1b6e24e77c85dcd105/src/main/java/com/lothrazar/cyclicmagic/item/random/PacketRandomize.java#L111

Solution:
Post the work to be done on the server thread onto the server/client thread, using 
``` java 
FMLCommonHandler.instance().getMinecraftServerInstance().addScheduledTask(() -> {
    //Work to be done on the server thread
});
```

As this is a very common pattern, I have abstracted this away in my mods using:
https://github.com/MineMaarten/Signals/blob/master/src/com/minemaarten/signals/network/AbstractPacket.java
https://github.com/MineMaarten/Signals/blob/master/src/com/minemaarten/signals/network/AbstractPacket.java
https://github.com/MineMaarten/Signals/blob/master/src/com/minemaarten/signals/proxy/ClientProxy.java#L103-L109

Let me know if you have any questions! Good luck!

**Comment by PrinceOfAmber** [comment]
Thanks for the great writeup. Looks like I do have addScheduledTask in use in many packets in the mod, but not others, and not in a base class.    Looks like i can get a quick fix in right away, sorry for being away so long.

**Comment by PrinceOfAmber** [comment]
1.17.3 https://minecraft.curseforge.com/projects/cyclic/files/2625191

**Comment by MineMaarten** [comment]
You're welcome! Looks good, thanks :).
