### ISSUE TITLE
Clientside Crash when opening Diamond Anvil GUI

### ISSUE THREAD

**Issue by ParadoxBomb** [PrinceOfAmber/Cyclic#912]
Minecraft version & Mod Version:
Minecraft 1.12.2
Cyclic 1.17.0 

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Clientside crash when trying to access the inventory of a diamond anvil with a tinker tool inside. Unsure just where the issue is here.

Crash log (if any):
VanillaFix was used to capture the crash
https://paste.dimdev.org/komurisaju.mccrash

**Comment by PrinceOfAmber** [comment]
Cannot replicate in my environment or in the modpacks I checked.  Cyclic does nothing special here, must be caused by either  com.infinityraider.infinitylib . Why infinitylib is trying to render things in GUI of other mods i have no idea.


Reference
https://github.com/PrinceOfAmber/Cyclic/blob/9f5eaea30c3f5f6342e7ff299f192990ea6bc507/src/main/java/com/lothrazar/cyclicmagic/block/anvil/GuiAnvilAuto.java#L46
